[2025-02-17 17:23:49,957][flwr][INFO] - Starting Flower ServerApp, config: num_rounds=20, no round_timeout
[2025-02-17 17:23:49,959][flwr][INFO] - 
[2025-02-17 17:23:49,962][flwr][INFO] - [INIT]
[2025-02-17 17:23:49,963][flwr][INFO] - Using initial global parameters provided by strategy
[2025-02-17 17:23:49,963][flwr][INFO] - Starting evaluation of initial global parameters
[2025-02-17 17:23:56,594][flwr][INFO] - initial parameters (loss, other metrics): 0.07204539165496826, {'accuracy': 0.1096}
[2025-02-17 17:23:56,595][flwr][INFO] - 
[2025-02-17 17:23:56,595][flwr][INFO] - [ROUND 1]
[2025-02-17 17:23:56,595][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:24:09,122][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 17:24:13,794][flwr][INFO] - fit progress: (1, 0.07138892478942871, {'accuracy': 0.2161}, 17.198823325015837)
[2025-02-17 17:24:13,794][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:24:18,304][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 17:24:18,305][flwr][INFO] - 
[2025-02-17 17:24:18,305][flwr][INFO] - [ROUND 2]
[2025-02-17 17:24:18,305][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:24:25,029][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 17:24:29,730][flwr][INFO] - fit progress: (2, 0.07007967958450317, {'accuracy': 0.2848}, 33.13575705900439)
[2025-02-17 17:24:29,731][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:24:34,445][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 17:24:34,445][flwr][INFO] - 
[2025-02-17 17:24:34,446][flwr][INFO] - [ROUND 3]
[2025-02-17 17:24:34,446][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:24:41,160][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 17:24:45,922][flwr][INFO] - fit progress: (3, 0.06743518178462982, {'accuracy': 0.3497}, 49.32774707401404)
[2025-02-17 17:24:45,923][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:24:50,133][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 17:24:50,133][flwr][INFO] - 
[2025-02-17 17:24:50,134][flwr][INFO] - [ROUND 4]
[2025-02-17 17:24:50,134][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:24:57,149][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 17:25:01,800][flwr][INFO] - fit progress: (4, 0.06361267669200897, {'accuracy': 0.3713}, 65.20552150602452)
[2025-02-17 17:25:01,800][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:25:06,312][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 17:25:06,312][flwr][INFO] - 
[2025-02-17 17:25:06,313][flwr][INFO] - [ROUND 5]
[2025-02-17 17:25:06,313][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:25:13,027][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 17:25:17,699][flwr][INFO] - fit progress: (5, 0.05783917311429977, {'accuracy': 0.4235}, 81.1047519830172)
[2025-02-17 17:25:17,700][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:25:21,810][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 17:25:21,811][flwr][INFO] - 
[2025-02-17 17:25:21,811][flwr][INFO] - [ROUND 6]
[2025-02-17 17:25:21,811][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:25:28,726][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 17:25:33,251][flwr][INFO] - fit progress: (6, 0.05887424921989441, {'accuracy': 0.4522}, 96.65655465400778)
[2025-02-17 17:25:33,252][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:25:37,962][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 17:25:37,963][flwr][INFO] - 
[2025-02-17 17:25:37,963][flwr][INFO] - [ROUND 7]
[2025-02-17 17:25:37,963][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:25:44,779][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 17:25:49,341][flwr][INFO] - fit progress: (7, 0.07568494112491608, {'accuracy': 0.4607}, 112.74583150001126)
[2025-02-17 17:25:49,341][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:25:53,852][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 17:25:53,852][flwr][INFO] - 
[2025-02-17 17:25:53,852][flwr][INFO] - [ROUND 8]
[2025-02-17 17:25:53,852][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:26:00,466][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 17:26:05,575][flwr][INFO] - fit progress: (8, 0.10514409980773926, {'accuracy': 0.4668}, 128.97999019001145)
[2025-02-17 17:26:05,575][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:26:10,385][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 17:26:10,386][flwr][INFO] - 
[2025-02-17 17:26:10,386][flwr][INFO] - [ROUND 9]
[2025-02-17 17:26:10,386][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:26:17,402][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 17:26:21,728][flwr][INFO] - fit progress: (9, 0.15457216604948043, {'accuracy': 0.4614}, 145.13306429001386)
[2025-02-17 17:26:21,728][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:26:26,140][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 17:26:26,140][flwr][INFO] - 
[2025-02-17 17:26:26,140][flwr][INFO] - [ROUND 10]
[2025-02-17 17:26:26,141][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:26:32,855][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 17:26:37,657][flwr][INFO] - fit progress: (10, 0.2281421519756317, {'accuracy': 0.4447}, 161.0621374840266)
[2025-02-17 17:26:37,657][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:26:42,067][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 17:26:42,068][flwr][INFO] - 
[2025-02-17 17:26:42,068][flwr][INFO] - [ROUND 11]
[2025-02-17 17:26:42,068][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:26:58,401][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 17:27:10,034][datasets.load][WARNING] - Using the latest cached version of the dataset since ylecun/mnist couldn't be found on the Hugging Face Hub
[2025-02-17 17:27:10,035][datasets.packaged_modules.cache.cache][WARNING] - Found the latest cached dataset configuration 'mnist' at /home/theo_ubuntu/.cache/huggingface/datasets/ylecun___mnist/mnist/0.0.0/77f3279092a1c1579b2250db8eafed0ad422088c (last modified on Sun Feb 16 13:24:27 2025).
[2025-02-17 17:27:12,328][flwr][INFO] - fit progress: (11, 0.33373311076164247, {'accuracy': 0.4309}, 195.7329696380184)
[2025-02-17 17:27:12,328][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:27:24,202][flwr][ERROR] - An exception was raised when processing a message by RayBackend
[2025-02-17 17:27:24,202][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=23759, ip=172.27.85.201, actor_id=41c031d372940a1c566ce7b801000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7ffa780aeed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=23759, ip=172.27.85.201, actor_id=41c031d372940a1c566ce7b801000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7ffa780aeed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=23759, ip=172.27.85.201, actor_id=41c031d372940a1c566ce7b801000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7ffa780aeed0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c
[2025-02-17 17:27:24,204][flwr][ERROR] - Traceback (most recent call last):
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py", line 112, in worker
    out_mssg, updated_context = backend.process_message(message, context)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 187, in process_message
    raise ex
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 175, in process_message
    ) = self.pool.fetch_result_and_return_actor_to_pool(future)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 478, in fetch_result_and_return_actor_to_pool
    _, out_mssg, updated_context = ray.get(future)
                                   ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=23759, ip=172.27.85.201, actor_id=41c031d372940a1c566ce7b801000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7ffa780aeed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=23759, ip=172.27.85.201, actor_id=41c031d372940a1c566ce7b801000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7ffa780aeed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=23759, ip=172.27.85.201, actor_id=41c031d372940a1c566ce7b801000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7ffa780aeed0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

[2025-02-17 17:27:24,236][flwr][ERROR] - An exception was raised when processing a message by RayBackend
[2025-02-17 17:27:24,236][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=23761, ip=172.27.85.201, actor_id=a2026865c4820a843f45e85301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fcf88266ed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=23761, ip=172.27.85.201, actor_id=a2026865c4820a843f45e85301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fcf88266ed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=23761, ip=172.27.85.201, actor_id=a2026865c4820a843f45e85301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fcf88266ed0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c
[2025-02-17 17:27:24,237][flwr][ERROR] - Traceback (most recent call last):
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py", line 112, in worker
    out_mssg, updated_context = backend.process_message(message, context)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 187, in process_message
    raise ex
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 175, in process_message
    ) = self.pool.fetch_result_and_return_actor_to_pool(future)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 478, in fetch_result_and_return_actor_to_pool
    _, out_mssg, updated_context = ray.get(future)
                                   ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=23761, ip=172.27.85.201, actor_id=a2026865c4820a843f45e85301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fcf88266ed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=23761, ip=172.27.85.201, actor_id=a2026865c4820a843f45e85301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fcf88266ed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=23761, ip=172.27.85.201, actor_id=a2026865c4820a843f45e85301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fcf88266ed0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

[2025-02-17 17:27:45,906][flwr][ERROR] - An exception was raised when processing a message by RayBackend
[2025-02-17 17:27:45,907][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=23760, ip=172.27.85.201, actor_id=5bb4f8af998cc87e0e52420601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd018106ed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=23760, ip=172.27.85.201, actor_id=5bb4f8af998cc87e0e52420601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd018106ed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=23760, ip=172.27.85.201, actor_id=5bb4f8af998cc87e0e52420601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd018106ed0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c
[2025-02-17 17:27:45,907][flwr][ERROR] - Traceback (most recent call last):
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py", line 112, in worker
    out_mssg, updated_context = backend.process_message(message, context)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 187, in process_message
    raise ex
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 175, in process_message
    ) = self.pool.fetch_result_and_return_actor_to_pool(future)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 478, in fetch_result_and_return_actor_to_pool
    _, out_mssg, updated_context = ray.get(future)
                                   ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=23760, ip=172.27.85.201, actor_id=5bb4f8af998cc87e0e52420601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd018106ed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=23760, ip=172.27.85.201, actor_id=5bb4f8af998cc87e0e52420601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd018106ed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=23760, ip=172.27.85.201, actor_id=5bb4f8af998cc87e0e52420601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd018106ed0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

[2025-02-17 17:27:45,991][flwr][INFO] - aggregate_evaluate: received 7 results and 3 failures
[2025-02-17 17:27:45,991][flwr][INFO] - 
[2025-02-17 17:27:45,991][flwr][INFO] - [ROUND 12]
[2025-02-17 17:27:45,991][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:28:02,222][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 17:28:06,645][flwr][INFO] - fit progress: (12, 0.4786702585697174, {'accuracy': 0.4167}, 250.0498555310187)
[2025-02-17 17:28:06,645][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:28:10,755][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 17:28:10,755][flwr][INFO] - 
[2025-02-17 17:28:10,755][flwr][INFO] - [ROUND 13]
[2025-02-17 17:28:10,756][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:28:17,371][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 17:28:21,739][flwr][INFO] - fit progress: (13, 0.676754530620575, {'accuracy': 0.402}, 265.14447409301647)
[2025-02-17 17:28:21,739][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:28:25,849][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 17:28:25,850][flwr][INFO] - 
[2025-02-17 17:28:25,850][flwr][INFO] - [ROUND 14]
[2025-02-17 17:28:25,850][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:28:32,565][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 17:28:36,870][flwr][INFO] - fit progress: (14, 0.9367212267875671, {'accuracy': 0.396}, 280.27573986400967)
[2025-02-17 17:28:36,871][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:28:41,282][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 17:28:41,282][flwr][INFO] - 
[2025-02-17 17:28:41,283][flwr][INFO] - [ROUND 15]
[2025-02-17 17:28:41,283][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:28:48,100][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 17:28:52,783][flwr][INFO] - fit progress: (15, 1.2754944820404053, {'accuracy': 0.3895}, 296.1885860550101)
[2025-02-17 17:28:52,784][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:28:58,798][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 17:28:58,799][flwr][INFO] - 
[2025-02-17 17:28:58,799][flwr][INFO] - [ROUND 16]
[2025-02-17 17:28:58,799][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:29:05,616][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 17:29:10,595][flwr][INFO] - fit progress: (16, 1.7151289346694947, {'accuracy': 0.3836}, 314.00003020401346)
[2025-02-17 17:29:10,595][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:29:14,605][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 17:29:14,605][flwr][INFO] - 
[2025-02-17 17:29:14,605][flwr][INFO] - [ROUND 17]
[2025-02-17 17:29:14,606][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:29:21,219][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 17:29:25,820][flwr][INFO] - fit progress: (17, 2.265795802307129, {'accuracy': 0.3809}, 329.2253008990083)
[2025-02-17 17:29:25,820][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:29:30,432][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 17:29:30,432][flwr][INFO] - 
[2025-02-17 17:29:30,432][flwr][INFO] - [ROUND 18]
[2025-02-17 17:29:30,433][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:29:37,048][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 17:29:41,383][flwr][INFO] - fit progress: (18, 2.9595915660858156, {'accuracy': 0.3798}, 344.78871360301855)
[2025-02-17 17:29:41,384][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:29:45,497][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 17:29:45,497][flwr][INFO] - 
[2025-02-17 17:29:45,497][flwr][INFO] - [ROUND 19]
[2025-02-17 17:29:45,498][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:29:52,414][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 17:29:56,782][flwr][INFO] - fit progress: (19, 3.8006108165740966, {'accuracy': 0.3766}, 360.1870039589994)
[2025-02-17 17:29:56,782][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:30:00,991][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 17:30:00,992][flwr][INFO] - 
[2025-02-17 17:30:00,992][flwr][INFO] - [ROUND 20]
[2025-02-17 17:30:00,992][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:30:08,408][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 17:30:12,723][flwr][INFO] - fit progress: (20, 4.826972286605835, {'accuracy': 0.3741}, 376.12842544101295)
[2025-02-17 17:30:12,723][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:30:17,033][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 17:30:17,034][flwr][INFO] - 
[2025-02-17 17:30:17,034][flwr][INFO] - [SUMMARY]
[2025-02-17 17:30:17,034][flwr][INFO] - Run finished 20 round(s) in 380.44s
[2025-02-17 17:30:17,035][flwr][INFO] - 	History (loss, distributed):
[2025-02-17 17:30:17,035][flwr][INFO] - 		round 1: 0.07611706058184306
[2025-02-17 17:30:17,035][flwr][INFO] - 		round 2: 0.07494701047738392
[2025-02-17 17:30:17,035][flwr][INFO] - 		round 3: 0.07239192148049672
[2025-02-17 17:30:17,035][flwr][INFO] - 		round 4: 0.06830960631370545
[2025-02-17 17:30:17,035][flwr][INFO] - 		round 5: 0.061899652083714805
[2025-02-17 17:30:17,035][flwr][INFO] - 		round 6: 0.06203203250964483
[2025-02-17 17:30:17,035][flwr][INFO] - 		round 7: 0.07869878133138021
[2025-02-17 17:30:17,035][flwr][INFO] - 		round 8: 0.1087521689136823
[2025-02-17 17:30:17,035][flwr][INFO] - 		round 9: 0.160697013537089
[2025-02-17 17:30:17,036][flwr][INFO] - 		round 10: 0.23822869261105856
[2025-02-17 17:30:17,036][flwr][INFO] - 		round 11: 0.3494327970913478
[2025-02-17 17:30:17,036][flwr][INFO] - 		round 12: 0.5002604007720948
[2025-02-17 17:30:17,036][flwr][INFO] - 		round 13: 0.7106709297498067
[2025-02-17 17:30:17,036][flwr][INFO] - 		round 14: 0.9866862249374388
[2025-02-17 17:30:17,036][flwr][INFO] - 		round 15: 1.3538630374272664
[2025-02-17 17:30:17,036][flwr][INFO] - 		round 16: 1.8328157107035317
[2025-02-17 17:30:17,036][flwr][INFO] - 		round 17: 2.4345014890034995
[2025-02-17 17:30:17,036][flwr][INFO] - 		round 18: 3.1924263159434
[2025-02-17 17:30:17,036][flwr][INFO] - 		round 19: 4.110333970387776
[2025-02-17 17:30:17,036][flwr][INFO] - 		round 20: 5.232224807739258
[2025-02-17 17:30:17,036][flwr][INFO] - 	History (loss, centralized):
[2025-02-17 17:30:17,036][flwr][INFO] - 		round 0: 0.07204539165496826
[2025-02-17 17:30:17,036][flwr][INFO] - 		round 1: 0.07138892478942871
[2025-02-17 17:30:17,037][flwr][INFO] - 		round 2: 0.07007967958450317
[2025-02-17 17:30:17,037][flwr][INFO] - 		round 3: 0.06743518178462982
[2025-02-17 17:30:17,037][flwr][INFO] - 		round 4: 0.06361267669200897
[2025-02-17 17:30:17,037][flwr][INFO] - 		round 5: 0.05783917311429977
[2025-02-17 17:30:17,037][flwr][INFO] - 		round 6: 0.05887424921989441
[2025-02-17 17:30:17,037][flwr][INFO] - 		round 7: 0.07568494112491608
[2025-02-17 17:30:17,037][flwr][INFO] - 		round 8: 0.10514409980773926
[2025-02-17 17:30:17,037][flwr][INFO] - 		round 9: 0.15457216604948043
[2025-02-17 17:30:17,037][flwr][INFO] - 		round 10: 0.2281421519756317
[2025-02-17 17:30:17,037][flwr][INFO] - 		round 11: 0.33373311076164247
[2025-02-17 17:30:17,037][flwr][INFO] - 		round 12: 0.4786702585697174
[2025-02-17 17:30:17,037][flwr][INFO] - 		round 13: 0.676754530620575
[2025-02-17 17:30:17,038][flwr][INFO] - 		round 14: 0.9367212267875671
[2025-02-17 17:30:17,038][flwr][INFO] - 		round 15: 1.2754944820404053
[2025-02-17 17:30:17,038][flwr][INFO] - 		round 16: 1.7151289346694947
[2025-02-17 17:30:17,038][flwr][INFO] - 		round 17: 2.265795802307129
[2025-02-17 17:30:17,038][flwr][INFO] - 		round 18: 2.9595915660858156
[2025-02-17 17:30:17,038][flwr][INFO] - 		round 19: 3.8006108165740966
[2025-02-17 17:30:17,038][flwr][INFO] - 		round 20: 4.826972286605835
[2025-02-17 17:30:17,038][flwr][INFO] - 	History (metrics, distributed, fit):
[2025-02-17 17:30:17,038][flwr][INFO] - 	{'clients_epsilons': [(1, 1.0),
[2025-02-17 17:30:17,038][flwr][INFO] - 	                      (2, 1.0),
[2025-02-17 17:30:17,038][flwr][INFO] - 	                      (3, 1.0),
[2025-02-17 17:30:17,038][flwr][INFO] - 	                      (4, 1.0),
[2025-02-17 17:30:17,038][flwr][INFO] - 	                      (5, 1.0),
[2025-02-17 17:30:17,038][flwr][INFO] - 	                      (6, 1.0),
[2025-02-17 17:30:17,039][flwr][INFO] - 	                      (7, 1.0),
[2025-02-17 17:30:17,039][flwr][INFO] - 	                      (8, 1.0),
[2025-02-17 17:30:17,039][flwr][INFO] - 	                      (9, 1.0),
[2025-02-17 17:30:17,039][flwr][INFO] - 	                      (10, 1.0),
[2025-02-17 17:30:17,039][flwr][INFO] - 	                      (11, 1.0),
[2025-02-17 17:30:17,039][flwr][INFO] - 	                      (12, 1.0),
[2025-02-17 17:30:17,039][flwr][INFO] - 	                      (13, 1.0),
[2025-02-17 17:30:17,039][flwr][INFO] - 	                      (14, 1.0),
[2025-02-17 17:30:17,039][flwr][INFO] - 	                      (15, 1.0),
[2025-02-17 17:30:17,039][flwr][INFO] - 	                      (16, 1.0),
[2025-02-17 17:30:17,039][flwr][INFO] - 	                      (17, 1.0),
[2025-02-17 17:30:17,040][flwr][INFO] - 	                      (18, 1.0),
[2025-02-17 17:30:17,040][flwr][INFO] - 	                      (19, 1.0),
[2025-02-17 17:30:17,040][flwr][INFO] - 	                      (20, 1.0)],
[2025-02-17 17:30:17,040][flwr][INFO] - 	 'clients_losses': [(1, 2.2926490402221678),
[2025-02-17 17:30:17,040][flwr][INFO] - 	                    (2, 2.2653742361068727),
[2025-02-17 17:30:17,040][flwr][INFO] - 	                    (3, 2.202857675552368),
[2025-02-17 17:30:17,040][flwr][INFO] - 	                    (4, 2.0967286920547483),
[2025-02-17 17:30:17,040][flwr][INFO] - 	                    (5, 1.9493018809954326),
[2025-02-17 17:30:17,040][flwr][INFO] - 	                    (6, 1.8381652673085531),
[2025-02-17 17:30:17,041][flwr][INFO] - 	                    (7, 2.0553414312998455),
[2025-02-17 17:30:17,041][flwr][INFO] - 	                    (8, 2.7056278427441915),
[2025-02-17 17:30:17,041][flwr][INFO] - 	                    (9, 3.8116197029749554),
[2025-02-17 17:30:17,041][flwr][INFO] - 	                    (10, 5.573540995915731),
[2025-02-17 17:30:17,041][flwr][INFO] - 	                    (11, 8.158458615938823),
[2025-02-17 17:30:17,041][flwr][INFO] - 	                    (12, 11.811882912317913),
[2025-02-17 17:30:17,041][flwr][INFO] - 	                    (13, 16.805966374079386),
[2025-02-17 17:30:17,041][flwr][INFO] - 	                    (14, 23.627677364349367),
[2025-02-17 17:30:17,041][flwr][INFO] - 	                    (15, 32.45933773040772),
[2025-02-17 17:30:17,042][flwr][INFO] - 	                    (16, 44.065459111531574),
[2025-02-17 17:30:17,042][flwr][INFO] - 	                    (17, 58.969344228108724),
[2025-02-17 17:30:17,042][flwr][INFO] - 	                    (18, 77.77546445210774),
[2025-02-17 17:30:17,042][flwr][INFO] - 	                    (19, 101.05238667805989),
[2025-02-17 17:30:17,042][flwr][INFO] - 	                    (20, 129.24794675191242)]}
[2025-02-17 17:30:17,042][flwr][INFO] - 	History (metrics, distributed, evaluate):
[2025-02-17 17:30:17,042][flwr][INFO] - 	{'clients_accuracies': [(1, 0.2141666666666667),
[2025-02-17 17:30:17,042][flwr][INFO] - 	                        (2, 0.26916666666666667),
[2025-02-17 17:30:17,042][flwr][INFO] - 	                        (3, 0.3483333333333333),
[2025-02-17 17:30:17,043][flwr][INFO] - 	                        (4, 0.37666666666666665),
[2025-02-17 17:30:17,043][flwr][INFO] - 	                        (5, 0.43166666666666675),
[2025-02-17 17:30:17,043][flwr][INFO] - 	                        (6, 0.46749999999999997),
[2025-02-17 17:30:17,043][flwr][INFO] - 	                        (7, 0.4791666666666667),
[2025-02-17 17:30:17,043][flwr][INFO] - 	                        (8, 0.48166666666666663),
[2025-02-17 17:30:17,043][flwr][INFO] - 	                        (9, 0.46333333333333326),
[2025-02-17 17:30:17,043][flwr][INFO] - 	                        (10, 0.4408333333333333),
[2025-02-17 17:30:17,043][flwr][INFO] - 	                        (11, 0.4297619047619047),
[2025-02-17 17:30:17,043][flwr][INFO] - 	                        (12, 0.4125),
[2025-02-17 17:30:17,043][flwr][INFO] - 	                        (13, 0.4058333333333334),
[2025-02-17 17:30:17,043][flwr][INFO] - 	                        (14, 0.38999999999999996),
[2025-02-17 17:30:17,043][flwr][INFO] - 	                        (15, 0.3808333333333333),
[2025-02-17 17:30:17,043][flwr][INFO] - 	                        (16, 0.3675),
[2025-02-17 17:30:17,043][flwr][INFO] - 	                        (17, 0.3616666666666667),
[2025-02-17 17:30:17,043][flwr][INFO] - 	                        (18, 0.3625),
[2025-02-17 17:30:17,044][flwr][INFO] - 	                        (19, 0.35833333333333334),
[2025-02-17 17:30:17,044][flwr][INFO] - 	                        (20, 0.35666666666666674)],
[2025-02-17 17:30:17,044][flwr][INFO] - 	 'clients_losses': [(1, 0.07611706058184306),
[2025-02-17 17:30:17,044][flwr][INFO] - 	                    (2, 0.07494701047738392),
[2025-02-17 17:30:17,044][flwr][INFO] - 	                    (3, 0.07239192148049672),
[2025-02-17 17:30:17,044][flwr][INFO] - 	                    (4, 0.06830960631370545),
[2025-02-17 17:30:17,044][flwr][INFO] - 	                    (5, 0.061899652083714805),
[2025-02-17 17:30:17,044][flwr][INFO] - 	                    (6, 0.06203203250964483),
[2025-02-17 17:30:17,044][flwr][INFO] - 	                    (7, 0.07869878133138021),
[2025-02-17 17:30:17,044][flwr][INFO] - 	                    (8, 0.1087521689136823),
[2025-02-17 17:30:17,044][flwr][INFO] - 	                    (9, 0.160697013537089),
[2025-02-17 17:30:17,044][flwr][INFO] - 	                    (10, 0.23822869261105856),
[2025-02-17 17:30:17,044][flwr][INFO] - 	                    (11, 0.3494327970913478),
[2025-02-17 17:30:17,045][flwr][INFO] - 	                    (12, 0.5002604007720948),
[2025-02-17 17:30:17,045][flwr][INFO] - 	                    (13, 0.7106709297498067),
[2025-02-17 17:30:17,045][flwr][INFO] - 	                    (14, 0.9866862249374388),
[2025-02-17 17:30:17,045][flwr][INFO] - 	                    (15, 1.3538630374272664),
[2025-02-17 17:30:17,045][flwr][INFO] - 	                    (16, 1.8328157107035317),
[2025-02-17 17:30:17,045][flwr][INFO] - 	                    (17, 2.4345014890034995),
[2025-02-17 17:30:17,045][flwr][INFO] - 	                    (18, 3.1924263159434),
[2025-02-17 17:30:17,045][flwr][INFO] - 	                    (19, 4.110333970387776),
[2025-02-17 17:30:17,046][flwr][INFO] - 	                    (20, 5.232224807739258)]}
[2025-02-17 17:30:17,046][flwr][INFO] - 	History (metrics, centralized):
[2025-02-17 17:30:17,046][flwr][INFO] - 	{'accuracy': [(0, 0.1096),
[2025-02-17 17:30:17,046][flwr][INFO] - 	              (1, 0.2161),
[2025-02-17 17:30:17,046][flwr][INFO] - 	              (2, 0.2848),
[2025-02-17 17:30:17,046][flwr][INFO] - 	              (3, 0.3497),
[2025-02-17 17:30:17,046][flwr][INFO] - 	              (4, 0.3713),
[2025-02-17 17:30:17,046][flwr][INFO] - 	              (5, 0.4235),
[2025-02-17 17:30:17,046][flwr][INFO] - 	              (6, 0.4522),
[2025-02-17 17:30:17,046][flwr][INFO] - 	              (7, 0.4607),
[2025-02-17 17:30:17,046][flwr][INFO] - 	              (8, 0.4668),
[2025-02-17 17:30:17,046][flwr][INFO] - 	              (9, 0.4614),
[2025-02-17 17:30:17,046][flwr][INFO] - 	              (10, 0.4447),
[2025-02-17 17:30:17,047][flwr][INFO] - 	              (11, 0.4309),
[2025-02-17 17:30:17,047][flwr][INFO] - 	              (12, 0.4167),
[2025-02-17 17:30:17,047][flwr][INFO] - 	              (13, 0.402),
[2025-02-17 17:30:17,047][flwr][INFO] - 	              (14, 0.396),
[2025-02-17 17:30:17,047][flwr][INFO] - 	              (15, 0.3895),
[2025-02-17 17:30:17,047][flwr][INFO] - 	              (16, 0.3836),
[2025-02-17 17:30:17,047][flwr][INFO] - 	              (17, 0.3809),
[2025-02-17 17:30:17,047][flwr][INFO] - 	              (18, 0.3798),
[2025-02-17 17:30:17,047][flwr][INFO] - 	              (19, 0.3766),
[2025-02-17 17:30:17,047][flwr][INFO] - 	              (20, 0.3741)]}
[2025-02-17 17:30:17,047][flwr][INFO] - 
