[2025-02-17 16:30:54,667][flwr][INFO] - Starting Flower ServerApp, config: num_rounds=20, no round_timeout
[2025-02-17 16:30:54,668][flwr][INFO] - 
[2025-02-17 16:30:54,669][flwr][INFO] - [INIT]
[2025-02-17 16:30:54,670][flwr][INFO] - Using initial global parameters provided by strategy
[2025-02-17 16:30:54,670][flwr][INFO] - Starting evaluation of initial global parameters
[2025-02-17 16:31:01,324][flwr][INFO] - initial parameters (loss, other metrics): 0.07237841854095459, {'accuracy': 0.0628}
[2025-02-17 16:31:01,324][flwr][INFO] - 
[2025-02-17 16:31:01,324][flwr][INFO] - [ROUND 1]
[2025-02-17 16:31:01,324][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 16:31:16,254][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 16:31:21,309][flwr][INFO] - fit progress: (1, 0.07164137234687805, {'accuracy': 0.1742}, 19.985365600994555)
[2025-02-17 16:31:21,310][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 16:31:25,719][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 16:31:25,720][flwr][INFO] - 
[2025-02-17 16:31:25,720][flwr][INFO] - [ROUND 2]
[2025-02-17 16:31:25,720][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 16:31:34,837][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 16:31:39,345][flwr][INFO] - fit progress: (2, 0.07085938069820404, {'accuracy': 0.2461}, 38.02155512099853)
[2025-02-17 16:31:39,346][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 16:31:44,256][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 16:31:44,256][flwr][INFO] - 
[2025-02-17 16:31:44,256][flwr][INFO] - [ROUND 3]
[2025-02-17 16:31:44,256][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 16:31:53,373][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 16:31:59,362][flwr][INFO] - fit progress: (3, 0.0694284102678299, {'accuracy': 0.3257}, 58.03840246901382)
[2025-02-17 16:31:59,362][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 16:32:04,372][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 16:32:04,372][flwr][INFO] - 
[2025-02-17 16:32:04,372][flwr][INFO] - [ROUND 4]
[2025-02-17 16:32:04,373][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 16:32:15,696][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 16:32:20,835][flwr][INFO] - fit progress: (4, 0.06644877095222473, {'accuracy': 0.3964}, 79.51167813999928)
[2025-02-17 16:32:20,836][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 16:32:27,849][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 16:32:27,849][flwr][INFO] - 
[2025-02-17 16:32:27,849][flwr][INFO] - [ROUND 5]
[2025-02-17 16:32:27,849][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 16:32:36,766][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 16:32:41,326][flwr][INFO] - fit progress: (5, 0.060932054793834685, {'accuracy': 0.455}, 100.00258040000335)
[2025-02-17 16:32:41,327][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 16:32:47,038][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 16:32:47,039][flwr][INFO] - 
[2025-02-17 16:32:47,039][flwr][INFO] - [ROUND 6]
[2025-02-17 16:32:47,039][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 16:32:55,756][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 16:33:00,691][flwr][INFO] - fit progress: (6, 0.05268532880544662, {'accuracy': 0.5472}, 119.36678558099084)
[2025-02-17 16:33:00,691][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 16:33:04,899][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 16:33:04,900][flwr][INFO] - 
[2025-02-17 16:33:04,900][flwr][INFO] - [ROUND 7]
[2025-02-17 16:33:04,900][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 16:33:13,815][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 16:33:18,298][flwr][INFO] - fit progress: (7, 0.0440220475435257, {'accuracy': 0.5793}, 136.9744026749977)
[2025-02-17 16:33:18,298][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 16:33:24,109][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 16:33:24,110][flwr][INFO] - 
[2025-02-17 16:33:24,110][flwr][INFO] - [ROUND 8]
[2025-02-17 16:33:24,110][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 16:33:44,343][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 16:33:58,527][flwr][INFO] - fit progress: (8, 0.039034076571464536, {'accuracy': 0.5986}, 177.20291889700457)
[2025-02-17 16:33:58,527][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 16:34:13,451][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 16:34:13,451][flwr][INFO] - 
[2025-02-17 16:34:13,452][flwr][INFO] - [ROUND 9]
[2025-02-17 16:34:13,452][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 16:34:24,073][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 16:34:29,216][flwr][INFO] - fit progress: (9, 0.037130385088920595, {'accuracy': 0.626}, 207.8921294340107)
[2025-02-17 16:34:29,216][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 16:34:33,229][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 16:34:33,230][flwr][INFO] - 
[2025-02-17 16:34:33,230][flwr][INFO] - [ROUND 10]
[2025-02-17 16:34:33,230][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 16:34:42,749][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 16:34:47,149][flwr][INFO] - fit progress: (10, 0.03844370397925377, {'accuracy': 0.645}, 225.82483298701118)
[2025-02-17 16:34:47,149][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 16:34:53,462][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 16:34:53,462][flwr][INFO] - 
[2025-02-17 16:34:53,462][flwr][INFO] - [ROUND 11]
[2025-02-17 16:34:53,462][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 16:35:02,881][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 16:35:07,278][flwr][INFO] - fit progress: (11, 0.043491725981235504, {'accuracy': 0.6478}, 245.9540324539994)
[2025-02-17 16:35:07,278][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 16:35:13,490][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 16:35:13,490][flwr][INFO] - 
[2025-02-17 16:35:13,490][flwr][INFO] - [ROUND 12]
[2025-02-17 16:35:13,491][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 16:35:22,509][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 16:35:26,847][flwr][INFO] - fit progress: (12, 0.05196981800794601, {'accuracy': 0.6426}, 265.5230478839949)
[2025-02-17 16:35:26,847][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 16:35:31,257][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 16:35:31,257][flwr][INFO] - 
[2025-02-17 16:35:31,257][flwr][INFO] - [ROUND 13]
[2025-02-17 16:35:31,257][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 16:35:40,476][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 16:35:44,831][flwr][INFO] - fit progress: (13, 0.06435967844724655, {'accuracy': 0.6313}, 283.5075262649916)
[2025-02-17 16:35:44,832][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 16:35:49,642][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 16:35:49,642][flwr][INFO] - 
[2025-02-17 16:35:49,642][flwr][INFO] - [ROUND 14]
[2025-02-17 16:35:49,642][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 16:35:58,962][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 16:36:03,258][flwr][INFO] - fit progress: (14, 0.08103436734080315, {'accuracy': 0.616}, 301.9340391610167)
[2025-02-17 16:36:03,258][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 16:36:07,970][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 16:36:07,970][flwr][INFO] - 
[2025-02-17 16:36:07,970][flwr][INFO] - [ROUND 15]
[2025-02-17 16:36:07,970][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 16:36:17,088][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 16:36:21,587][flwr][INFO] - fit progress: (15, 0.10294537661075592, {'accuracy': 0.6016}, 320.2628173629928)
[2025-02-17 16:36:21,587][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 16:36:25,996][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 16:36:25,996][flwr][INFO] - 
[2025-02-17 16:36:25,997][flwr][INFO] - [ROUND 16]
[2025-02-17 16:36:25,997][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 16:38:27,643][flwr][ERROR] - An exception was raised when processing a message by RayBackend
[2025-02-17 16:38:27,643][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=9095, ip=172.27.85.201, actor_id=e6a0d6cfa95ad78daae7263c01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9b63e5ed90>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=9095, ip=172.27.85.201, actor_id=e6a0d6cfa95ad78daae7263c01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9b63e5ed90>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=9095, ip=172.27.85.201, actor_id=e6a0d6cfa95ad78daae7263c01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9b63e5ed90>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c
[2025-02-17 16:38:27,646][flwr][ERROR] - Traceback (most recent call last):
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py", line 112, in worker
    out_mssg, updated_context = backend.process_message(message, context)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 187, in process_message
    raise ex
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 175, in process_message
    ) = self.pool.fetch_result_and_return_actor_to_pool(future)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 478, in fetch_result_and_return_actor_to_pool
    _, out_mssg, updated_context = ray.get(future)
                                   ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=9095, ip=172.27.85.201, actor_id=e6a0d6cfa95ad78daae7263c01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9b63e5ed90>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=9095, ip=172.27.85.201, actor_id=e6a0d6cfa95ad78daae7263c01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9b63e5ed90>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=9095, ip=172.27.85.201, actor_id=e6a0d6cfa95ad78daae7263c01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9b63e5ed90>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

[2025-02-17 16:38:27,840][flwr][ERROR] - An exception was raised when processing a message by RayBackend
[2025-02-17 16:38:27,840][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=9092, ip=172.27.85.201, actor_id=fa5fa3b305552b0f4c74c84d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f84c81e05d0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=9092, ip=172.27.85.201, actor_id=fa5fa3b305552b0f4c74c84d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f84c81e05d0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=9092, ip=172.27.85.201, actor_id=fa5fa3b305552b0f4c74c84d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f84c81e05d0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c
[2025-02-17 16:38:27,841][flwr][ERROR] - Traceback (most recent call last):
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py", line 112, in worker
    out_mssg, updated_context = backend.process_message(message, context)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 187, in process_message
    raise ex
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 175, in process_message
    ) = self.pool.fetch_result_and_return_actor_to_pool(future)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 478, in fetch_result_and_return_actor_to_pool
    _, out_mssg, updated_context = ray.get(future)
                                   ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=9092, ip=172.27.85.201, actor_id=fa5fa3b305552b0f4c74c84d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f84c81e05d0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=9092, ip=172.27.85.201, actor_id=fa5fa3b305552b0f4c74c84d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f84c81e05d0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=9092, ip=172.27.85.201, actor_id=fa5fa3b305552b0f4c74c84d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f84c81e05d0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

[2025-02-17 16:38:27,916][flwr][ERROR] - An exception was raised when processing a message by RayBackend
[2025-02-17 16:38:27,916][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=9097, ip=172.27.85.201, actor_id=c4143a4a74ce96974f9131df01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f325c202f90>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=9097, ip=172.27.85.201, actor_id=c4143a4a74ce96974f9131df01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f325c202f90>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=9097, ip=172.27.85.201, actor_id=c4143a4a74ce96974f9131df01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f325c202f90>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c
[2025-02-17 16:38:27,917][flwr][ERROR] - Traceback (most recent call last):
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py", line 112, in worker
    out_mssg, updated_context = backend.process_message(message, context)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 187, in process_message
    raise ex
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 175, in process_message
    ) = self.pool.fetch_result_and_return_actor_to_pool(future)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 478, in fetch_result_and_return_actor_to_pool
    _, out_mssg, updated_context = ray.get(future)
                                   ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=9097, ip=172.27.85.201, actor_id=c4143a4a74ce96974f9131df01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f325c202f90>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=9097, ip=172.27.85.201, actor_id=c4143a4a74ce96974f9131df01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f325c202f90>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=9097, ip=172.27.85.201, actor_id=c4143a4a74ce96974f9131df01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f325c202f90>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

[2025-02-17 16:38:29,702][flwr][INFO] - aggregate_fit: received 7 results and 3 failures
[2025-02-17 16:38:34,446][flwr][INFO] - fit progress: (16, 0.13092965945005416, {'accuracy': 0.587}, 453.12210409200634)
[2025-02-17 16:38:34,446][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 16:38:39,457][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 16:38:39,458][flwr][INFO] - 
[2025-02-17 16:38:39,458][flwr][INFO] - [ROUND 17]
[2025-02-17 16:38:39,458][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 16:38:48,877][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 16:38:53,789][flwr][INFO] - fit progress: (17, 0.16632903451919556, {'accuracy': 0.5707}, 472.4647738749918)
[2025-02-17 16:38:53,789][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 16:38:58,599][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 16:38:58,599][flwr][INFO] - 
[2025-02-17 16:38:58,599][flwr][INFO] - [ROUND 18]
[2025-02-17 16:38:58,599][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 16:39:08,418][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 16:39:13,054][flwr][INFO] - fit progress: (18, 0.20922054319381714, {'accuracy': 0.5543}, 491.7297995109984)
[2025-02-17 16:39:13,056][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 16:39:17,968][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 16:39:17,968][flwr][INFO] - 
[2025-02-17 16:39:17,968][flwr][INFO] - [ROUND 19]
[2025-02-17 16:39:17,969][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 16:39:27,388][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 16:39:31,685][flwr][INFO] - fit progress: (19, 0.26265740082263944, {'accuracy': 0.5403}, 510.3610192830092)
[2025-02-17 16:39:31,685][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 16:39:36,094][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 16:39:36,095][flwr][INFO] - 
[2025-02-17 16:39:36,095][flwr][INFO] - [ROUND 20]
[2025-02-17 16:39:36,095][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 16:39:45,614][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 16:39:50,574][flwr][INFO] - fit progress: (20, 0.32753600978851316, {'accuracy': 0.5245}, 529.2497780419944)
[2025-02-17 16:39:50,574][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 16:39:55,684][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 16:39:55,684][flwr][INFO] - 
[2025-02-17 16:39:55,684][flwr][INFO] - [SUMMARY]
[2025-02-17 16:39:55,684][flwr][INFO] - Run finished 20 round(s) in 534.36s
[2025-02-17 16:39:55,685][flwr][INFO] - 	History (loss, distributed):
[2025-02-17 16:39:55,685][flwr][INFO] - 		round 1: 0.07638222674528758
[2025-02-17 16:39:55,685][flwr][INFO] - 		round 2: 0.0755471662680308
[2025-02-17 16:39:55,685][flwr][INFO] - 		round 3: 0.07404825568199157
[2025-02-17 16:39:55,685][flwr][INFO] - 		round 4: 0.0709597671031952
[2025-02-17 16:39:55,685][flwr][INFO] - 		round 5: 0.06537986169258754
[2025-02-17 16:39:55,685][flwr][INFO] - 		round 6: 0.057125410238901775
[2025-02-17 16:39:55,685][flwr][INFO] - 		round 7: 0.0483125713467598
[2025-02-17 16:39:55,686][flwr][INFO] - 		round 8: 0.043338978687922164
[2025-02-17 16:39:55,686][flwr][INFO] - 		round 9: 0.04164531692862511
[2025-02-17 16:39:55,686][flwr][INFO] - 		round 10: 0.04299203691383203
[2025-02-17 16:39:55,686][flwr][INFO] - 		round 11: 0.04854442747930686
[2025-02-17 16:39:55,686][flwr][INFO] - 		round 12: 0.05798954193790754
[2025-02-17 16:39:55,686][flwr][INFO] - 		round 13: 0.07175047531723974
[2025-02-17 16:39:55,686][flwr][INFO] - 		round 14: 0.09067115580042204
[2025-02-17 16:39:55,686][flwr][INFO] - 		round 15: 0.11584818740685783
[2025-02-17 16:39:55,686][flwr][INFO] - 		round 16: 0.1481140093008677
[2025-02-17 16:39:55,686][flwr][INFO] - 		round 17: 0.18915064056714376
[2025-02-17 16:39:55,686][flwr][INFO] - 		round 18: 0.23976305067539214
[2025-02-17 16:39:55,686][flwr][INFO] - 		round 19: 0.3027079615990321
[2025-02-17 16:39:55,686][flwr][INFO] - 		round 20: 0.3785736680030822
[2025-02-17 16:39:55,686][flwr][INFO] - 	History (loss, centralized):
[2025-02-17 16:39:55,687][flwr][INFO] - 		round 0: 0.07237841854095459
[2025-02-17 16:39:55,687][flwr][INFO] - 		round 1: 0.07164137234687805
[2025-02-17 16:39:55,687][flwr][INFO] - 		round 2: 0.07085938069820404
[2025-02-17 16:39:55,687][flwr][INFO] - 		round 3: 0.0694284102678299
[2025-02-17 16:39:55,687][flwr][INFO] - 		round 4: 0.06644877095222473
[2025-02-17 16:39:55,687][flwr][INFO] - 		round 5: 0.060932054793834685
[2025-02-17 16:39:55,687][flwr][INFO] - 		round 6: 0.05268532880544662
[2025-02-17 16:39:55,687][flwr][INFO] - 		round 7: 0.0440220475435257
[2025-02-17 16:39:55,687][flwr][INFO] - 		round 8: 0.039034076571464536
[2025-02-17 16:39:55,687][flwr][INFO] - 		round 9: 0.037130385088920595
[2025-02-17 16:39:55,687][flwr][INFO] - 		round 10: 0.03844370397925377
[2025-02-17 16:39:55,687][flwr][INFO] - 		round 11: 0.043491725981235504
[2025-02-17 16:39:55,687][flwr][INFO] - 		round 12: 0.05196981800794601
[2025-02-17 16:39:55,688][flwr][INFO] - 		round 13: 0.06435967844724655
[2025-02-17 16:39:55,688][flwr][INFO] - 		round 14: 0.08103436734080315
[2025-02-17 16:39:55,688][flwr][INFO] - 		round 15: 0.10294537661075592
[2025-02-17 16:39:55,688][flwr][INFO] - 		round 16: 0.13092965945005416
[2025-02-17 16:39:55,688][flwr][INFO] - 		round 17: 0.16632903451919556
[2025-02-17 16:39:55,688][flwr][INFO] - 		round 18: 0.20922054319381714
[2025-02-17 16:39:55,688][flwr][INFO] - 		round 19: 0.26265740082263944
[2025-02-17 16:39:55,688][flwr][INFO] - 		round 20: 0.32753600978851316
[2025-02-17 16:39:55,688][flwr][INFO] - 	History (metrics, distributed, fit):
[2025-02-17 16:39:55,688][flwr][INFO] - 	{'clients_epsilons': [(1, 1.0),
[2025-02-17 16:39:55,688][flwr][INFO] - 	                      (2, 1.0),
[2025-02-17 16:39:55,688][flwr][INFO] - 	                      (3, 1.0),
[2025-02-17 16:39:55,688][flwr][INFO] - 	                      (4, 1.0),
[2025-02-17 16:39:55,688][flwr][INFO] - 	                      (5, 1.0),
[2025-02-17 16:39:55,689][flwr][INFO] - 	                      (6, 1.0),
[2025-02-17 16:39:55,689][flwr][INFO] - 	                      (7, 1.0),
[2025-02-17 16:39:55,689][flwr][INFO] - 	                      (8, 1.0),
[2025-02-17 16:39:55,689][flwr][INFO] - 	                      (9, 1.0),
[2025-02-17 16:39:55,689][flwr][INFO] - 	                      (10, 1.0),
[2025-02-17 16:39:55,689][flwr][INFO] - 	                      (11, 1.0),
[2025-02-17 16:39:55,689][flwr][INFO] - 	                      (12, 1.0),
[2025-02-17 16:39:55,689][flwr][INFO] - 	                      (13, 1.0),
[2025-02-17 16:39:55,689][flwr][INFO] - 	                      (14, 1.0),
[2025-02-17 16:39:55,689][flwr][INFO] - 	                      (15, 1.0),
[2025-02-17 16:39:55,689][flwr][INFO] - 	                      (16, 1.0),
[2025-02-17 16:39:55,689][flwr][INFO] - 	                      (17, 1.0),
[2025-02-17 16:39:55,689][flwr][INFO] - 	                      (18, 1.0),
[2025-02-17 16:39:55,689][flwr][INFO] - 	                      (19, 1.0),
[2025-02-17 16:39:55,690][flwr][INFO] - 	                      (20, 1.0)],
[2025-02-17 16:39:55,690][flwr][INFO] - 	 'clients_losses': [(1, 2.3034511868158978),
[2025-02-17 16:39:55,690][flwr][INFO] - 	                    (2, 2.2798924382527668),
[2025-02-17 16:39:55,690][flwr][INFO] - 	                    (3, 2.2475572220484414),
[2025-02-17 16:39:55,690][flwr][INFO] - 	                    (4, 2.184361623128255),
[2025-02-17 16:39:55,690][flwr][INFO] - 	                    (5, 2.059328382015228),
[2025-02-17 16:39:55,690][flwr][INFO] - 	                    (6, 1.8523676196734111),
[2025-02-17 16:39:55,690][flwr][INFO] - 	                    (7, 1.5840287319819133),
[2025-02-17 16:39:55,690][flwr][INFO] - 	                    (8, 1.353109896183014),
[2025-02-17 16:39:55,690][flwr][INFO] - 	                    (9, 1.2443354535102844),
[2025-02-17 16:39:55,690][flwr][INFO] - 	                    (10, 1.224728999932607),
[2025-02-17 16:39:55,690][flwr][INFO] - 	                    (11, 1.32606245358785),
[2025-02-17 16:39:55,691][flwr][INFO] - 	                    (12, 1.542499781847),
[2025-02-17 16:39:55,691][flwr][INFO] - 	                    (13, 1.8804765407244364),
[2025-02-17 16:39:55,691][flwr][INFO] - 	                    (14, 2.3480744751294456),
[2025-02-17 16:39:55,691][flwr][INFO] - 	                    (15, 2.9634935148557027),
[2025-02-17 16:39:55,691][flwr][INFO] - 	                    (16, 3.7959348213104973),
[2025-02-17 16:39:55,691][flwr][INFO] - 	                    (17, 4.764072351455688),
[2025-02-17 16:39:55,691][flwr][INFO] - 	                    (18, 6.006968196233114),
[2025-02-17 16:39:55,691][flwr][INFO] - 	                    (19, 7.5491988611221315),
[2025-02-17 16:39:55,691][flwr][INFO] - 	                    (20, 9.425229557355244)]}
[2025-02-17 16:39:55,692][flwr][INFO] - 	History (metrics, distributed, evaluate):
[2025-02-17 16:39:55,692][flwr][INFO] - 	{'clients_accuracies': [(1, 0.18833333333333332),
[2025-02-17 16:39:55,692][flwr][INFO] - 	                        (2, 0.25083333333333335),
[2025-02-17 16:39:55,692][flwr][INFO] - 	                        (3, 0.32666666666666666),
[2025-02-17 16:39:55,692][flwr][INFO] - 	                        (4, 0.39499999999999996),
[2025-02-17 16:39:55,692][flwr][INFO] - 	                        (5, 0.4583333333333333),
[2025-02-17 16:39:55,692][flwr][INFO] - 	                        (6, 0.5325),
[2025-02-17 16:39:55,692][flwr][INFO] - 	                        (7, 0.555),
[2025-02-17 16:39:55,692][flwr][INFO] - 	                        (8, 0.5675),
[2025-02-17 16:39:55,692][flwr][INFO] - 	                        (9, 0.6016666666666667),
[2025-02-17 16:39:55,692][flwr][INFO] - 	                        (10, 0.6233333333333334),
[2025-02-17 16:39:55,692][flwr][INFO] - 	                        (11, 0.6275000000000001),
[2025-02-17 16:39:55,692][flwr][INFO] - 	                        (12, 0.625),
[2025-02-17 16:39:55,692][flwr][INFO] - 	                        (13, 0.6183333333333334),
[2025-02-17 16:39:55,693][flwr][INFO] - 	                        (14, 0.6116666666666666),
[2025-02-17 16:39:55,693][flwr][INFO] - 	                        (15, 0.5933333333333334),
[2025-02-17 16:39:55,693][flwr][INFO] - 	                        (16, 0.5800000000000001),
[2025-02-17 16:39:55,693][flwr][INFO] - 	                        (17, 0.5558333333333334),
[2025-02-17 16:39:55,693][flwr][INFO] - 	                        (18, 0.5341666666666666),
[2025-02-17 16:39:55,693][flwr][INFO] - 	                        (19, 0.52),
[2025-02-17 16:39:55,693][flwr][INFO] - 	                        (20, 0.5091666666666665)],
[2025-02-17 16:39:55,693][flwr][INFO] - 	 'clients_losses': [(1, 0.07638222674528758),
[2025-02-17 16:39:55,693][flwr][INFO] - 	                    (2, 0.0755471662680308),
[2025-02-17 16:39:55,693][flwr][INFO] - 	                    (3, 0.07404825568199157),
[2025-02-17 16:39:55,693][flwr][INFO] - 	                    (4, 0.0709597671031952),
[2025-02-17 16:39:55,693][flwr][INFO] - 	                    (5, 0.06537986169258754),
[2025-02-17 16:39:55,693][flwr][INFO] - 	                    (6, 0.057125410238901775),
[2025-02-17 16:39:55,693][flwr][INFO] - 	                    (7, 0.0483125713467598),
[2025-02-17 16:39:55,694][flwr][INFO] - 	                    (8, 0.043338978687922164),
[2025-02-17 16:39:55,694][flwr][INFO] - 	                    (9, 0.04164531692862511),
[2025-02-17 16:39:55,694][flwr][INFO] - 	                    (10, 0.04299203691383203),
[2025-02-17 16:39:55,694][flwr][INFO] - 	                    (11, 0.04854442747930686),
[2025-02-17 16:39:55,694][flwr][INFO] - 	                    (12, 0.05798954193790754),
[2025-02-17 16:39:55,694][flwr][INFO] - 	                    (13, 0.07175047531723974),
[2025-02-17 16:39:55,694][flwr][INFO] - 	                    (14, 0.09067115580042204),
[2025-02-17 16:39:55,694][flwr][INFO] - 	                    (15, 0.11584818740685783),
[2025-02-17 16:39:55,694][flwr][INFO] - 	                    (16, 0.1481140093008677),
[2025-02-17 16:39:55,694][flwr][INFO] - 	                    (17, 0.18915064056714376),
[2025-02-17 16:39:55,694][flwr][INFO] - 	                    (18, 0.23976305067539214),
[2025-02-17 16:39:55,694][flwr][INFO] - 	                    (19, 0.3027079615990321),
[2025-02-17 16:39:55,694][flwr][INFO] - 	                    (20, 0.3785736680030822)]}
[2025-02-17 16:39:55,695][flwr][INFO] - 	History (metrics, centralized):
[2025-02-17 16:39:55,695][flwr][INFO] - 	{'accuracy': [(0, 0.0628),
[2025-02-17 16:39:55,695][flwr][INFO] - 	              (1, 0.1742),
[2025-02-17 16:39:55,695][flwr][INFO] - 	              (2, 0.2461),
[2025-02-17 16:39:55,695][flwr][INFO] - 	              (3, 0.3257),
[2025-02-17 16:39:55,695][flwr][INFO] - 	              (4, 0.3964),
[2025-02-17 16:39:55,695][flwr][INFO] - 	              (5, 0.455),
[2025-02-17 16:39:55,695][flwr][INFO] - 	              (6, 0.5472),
[2025-02-17 16:39:55,695][flwr][INFO] - 	              (7, 0.5793),
[2025-02-17 16:39:55,695][flwr][INFO] - 	              (8, 0.5986),
[2025-02-17 16:39:55,695][flwr][INFO] - 	              (9, 0.626),
[2025-02-17 16:39:55,695][flwr][INFO] - 	              (10, 0.645),
[2025-02-17 16:39:55,696][flwr][INFO] - 	              (11, 0.6478),
[2025-02-17 16:39:55,696][flwr][INFO] - 	              (12, 0.6426),
[2025-02-17 16:39:55,696][flwr][INFO] - 	              (13, 0.6313),
[2025-02-17 16:39:55,696][flwr][INFO] - 	              (14, 0.616),
[2025-02-17 16:39:55,696][flwr][INFO] - 	              (15, 0.6016),
[2025-02-17 16:39:55,696][flwr][INFO] - 	              (16, 0.587),
[2025-02-17 16:39:55,696][flwr][INFO] - 	              (17, 0.5707),
[2025-02-17 16:39:55,696][flwr][INFO] - 	              (18, 0.5543),
[2025-02-17 16:39:55,696][flwr][INFO] - 	              (19, 0.5403),
[2025-02-17 16:39:55,696][flwr][INFO] - 	              (20, 0.5245)]}
[2025-02-17 16:39:55,696][flwr][INFO] - 
