[2025-02-17 20:14:42,328][flwr][INFO] - Starting Flower ServerApp, config: num_rounds=20, no round_timeout
[2025-02-17 20:14:42,328][flwr][INFO] - 
[2025-02-17 20:14:42,329][flwr][INFO] - [INIT]
[2025-02-17 20:14:42,329][flwr][INFO] - Using initial global parameters provided by strategy
[2025-02-17 20:14:42,330][flwr][INFO] - Starting evaluation of initial global parameters
[2025-02-17 20:14:48,837][flwr][INFO] - initial parameters (loss, other metrics): 0.07214015040397644, {'accuracy': 0.0988}
[2025-02-17 20:14:48,837][flwr][INFO] - 
[2025-02-17 20:14:48,837][flwr][INFO] - [ROUND 1]
[2025-02-17 20:14:48,837][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 20:15:30,715][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-17 20:15:35,702][flwr][INFO] - fit progress: (1, 0.0718349406003952, {'accuracy': 0.1395}, 46.86510461100261)
[2025-02-17 20:15:35,703][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 20:15:55,067][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 20:15:55,067][flwr][INFO] - 
[2025-02-17 20:15:55,067][flwr][INFO] - [ROUND 2]
[2025-02-17 20:15:55,068][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 20:16:31,085][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-17 20:16:35,627][flwr][INFO] - fit progress: (2, 0.07129651372432709, {'accuracy': 0.1279}, 106.78972048001015)
[2025-02-17 20:16:35,627][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 20:16:50,994][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 20:16:50,994][flwr][INFO] - 
[2025-02-17 20:16:50,995][flwr][INFO] - [ROUND 3]
[2025-02-17 20:16:50,995][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 20:17:35,467][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-17 20:17:40,065][flwr][INFO] - fit progress: (3, 0.0699718425989151, {'accuracy': 0.3108}, 171.22813394700643)
[2025-02-17 20:17:40,065][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 20:17:56,196][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 20:17:56,197][flwr][INFO] - 
[2025-02-17 20:17:56,197][flwr][INFO] - [ROUND 4]
[2025-02-17 20:17:56,197][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 20:18:33,708][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-17 20:18:38,555][flwr][INFO] - fit progress: (4, 0.06690800302028656, {'accuracy': 0.4077}, 229.7183846340049)
[2025-02-17 20:18:38,556][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 20:18:55,402][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 20:18:55,402][flwr][INFO] - 
[2025-02-17 20:18:55,403][flwr][INFO] - [ROUND 5]
[2025-02-17 20:18:55,403][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 20:19:32,689][flwr][ERROR] - An exception was raised when processing a message by RayBackend
[2025-02-17 20:19:32,690][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=888, ip=172.27.85.201, actor_id=d6c91049775f8123b7578dce01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7efdcdff7710>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=888, ip=172.27.85.201, actor_id=d6c91049775f8123b7578dce01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7efdcdff7710>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=888, ip=172.27.85.201, actor_id=d6c91049775f8123b7578dce01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7efdcdff7710>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c
[2025-02-17 20:19:32,691][flwr][ERROR] - Traceback (most recent call last):
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py", line 112, in worker
    out_mssg, updated_context = backend.process_message(message, context)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 187, in process_message
    raise ex
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 175, in process_message
    ) = self.pool.fetch_result_and_return_actor_to_pool(future)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 478, in fetch_result_and_return_actor_to_pool
    _, out_mssg, updated_context = ray.get(future)
                                   ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=888, ip=172.27.85.201, actor_id=d6c91049775f8123b7578dce01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7efdcdff7710>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=888, ip=172.27.85.201, actor_id=d6c91049775f8123b7578dce01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7efdcdff7710>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=888, ip=172.27.85.201, actor_id=d6c91049775f8123b7578dce01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7efdcdff7710>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

[2025-02-17 20:19:38,255][flwr][ERROR] - An exception was raised when processing a message by RayBackend
[2025-02-17 20:19:38,255][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=887, ip=172.27.85.201, actor_id=a2c51d5b40ef09714e0d514301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f30ac4d2110>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=887, ip=172.27.85.201, actor_id=a2c51d5b40ef09714e0d514301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f30ac4d2110>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=887, ip=172.27.85.201, actor_id=a2c51d5b40ef09714e0d514301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f30ac4d2110>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c
[2025-02-17 20:19:38,256][flwr][ERROR] - Traceback (most recent call last):
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py", line 112, in worker
    out_mssg, updated_context = backend.process_message(message, context)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 187, in process_message
    raise ex
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 175, in process_message
    ) = self.pool.fetch_result_and_return_actor_to_pool(future)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 478, in fetch_result_and_return_actor_to_pool
    _, out_mssg, updated_context = ray.get(future)
                                   ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=887, ip=172.27.85.201, actor_id=a2c51d5b40ef09714e0d514301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f30ac4d2110>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=887, ip=172.27.85.201, actor_id=a2c51d5b40ef09714e0d514301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f30ac4d2110>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=887, ip=172.27.85.201, actor_id=a2c51d5b40ef09714e0d514301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f30ac4d2110>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

[2025-02-17 20:19:45,992][flwr][ERROR] - An exception was raised when processing a message by RayBackend
[2025-02-17 20:19:45,992][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=883, ip=172.27.85.201, actor_id=75781072397ee2fc123ebe5e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f78794b3d10>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=883, ip=172.27.85.201, actor_id=75781072397ee2fc123ebe5e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f78794b3d10>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=883, ip=172.27.85.201, actor_id=75781072397ee2fc123ebe5e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f78794b3d10>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c
[2025-02-17 20:19:45,993][flwr][ERROR] - Traceback (most recent call last):
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py", line 112, in worker
    out_mssg, updated_context = backend.process_message(message, context)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 187, in process_message
    raise ex
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 175, in process_message
    ) = self.pool.fetch_result_and_return_actor_to_pool(future)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 478, in fetch_result_and_return_actor_to_pool
    _, out_mssg, updated_context = ray.get(future)
                                   ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=883, ip=172.27.85.201, actor_id=75781072397ee2fc123ebe5e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f78794b3d10>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=883, ip=172.27.85.201, actor_id=75781072397ee2fc123ebe5e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f78794b3d10>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=883, ip=172.27.85.201, actor_id=75781072397ee2fc123ebe5e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f78794b3d10>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

[2025-02-17 20:19:46,091][flwr][INFO] - aggregate_fit: received 47 results and 3 failures
[2025-02-17 20:19:50,530][flwr][INFO] - fit progress: (5, 0.06129104617834091, {'accuracy': 0.4755}, 301.6933281740057)
[2025-02-17 20:19:50,531][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 20:20:08,443][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 20:20:08,444][flwr][INFO] - 
[2025-02-17 20:20:08,444][flwr][INFO] - [ROUND 6]
[2025-02-17 20:20:08,444][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 20:20:45,579][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-17 20:20:49,769][flwr][INFO] - fit progress: (6, 0.05262519137859344, {'accuracy': 0.5422}, 360.93243192500086)
[2025-02-17 20:20:49,770][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 20:21:04,881][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 20:21:04,882][flwr][INFO] - 
[2025-02-17 20:21:04,882][flwr][INFO] - [ROUND 7]
[2025-02-17 20:21:04,882][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 20:21:42,838][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-17 20:21:53,425][flwr][INFO] - fit progress: (7, 0.04293306818008423, {'accuracy': 0.6093}, 424.588369553996)
[2025-02-17 20:21:53,426][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 20:22:10,175][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 20:22:10,175][flwr][INFO] - 
[2025-02-17 20:22:10,175][flwr][INFO] - [ROUND 8]
[2025-02-17 20:22:10,175][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 20:22:46,193][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-17 20:22:50,852][flwr][INFO] - fit progress: (8, 0.03583903885483742, {'accuracy': 0.6433}, 482.01462613101467)
[2025-02-17 20:22:50,852][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 20:23:06,712][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 20:23:06,717][flwr][INFO] - 
[2025-02-17 20:23:06,717][flwr][INFO] - [ROUND 9]
[2025-02-17 20:23:06,717][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 20:23:44,445][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-17 20:23:48,633][flwr][INFO] - fit progress: (9, 0.033026599270105365, {'accuracy': 0.666}, 539.7960300980194)
[2025-02-17 20:23:48,633][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 20:24:04,936][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 20:24:04,937][flwr][INFO] - 
[2025-02-17 20:24:04,937][flwr][INFO] - [ROUND 10]
[2025-02-17 20:24:04,937][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 20:26:28,705][flwr][ERROR] - An exception was raised when processing a message by RayBackend
[2025-02-17 20:26:28,705][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=884, ip=172.27.85.201, actor_id=830a063435e40b2b6e8abc1b01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fcf3593eed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=884, ip=172.27.85.201, actor_id=830a063435e40b2b6e8abc1b01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fcf3593eed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=884, ip=172.27.85.201, actor_id=830a063435e40b2b6e8abc1b01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fcf3593eed0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c
[2025-02-17 20:26:28,706][flwr][ERROR] - Traceback (most recent call last):
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py", line 112, in worker
    out_mssg, updated_context = backend.process_message(message, context)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 187, in process_message
    raise ex
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 175, in process_message
    ) = self.pool.fetch_result_and_return_actor_to_pool(future)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 478, in fetch_result_and_return_actor_to_pool
    _, out_mssg, updated_context = ray.get(future)
                                   ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=884, ip=172.27.85.201, actor_id=830a063435e40b2b6e8abc1b01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fcf3593eed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=884, ip=172.27.85.201, actor_id=830a063435e40b2b6e8abc1b01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fcf3593eed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=884, ip=172.27.85.201, actor_id=830a063435e40b2b6e8abc1b01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fcf3593eed0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

[2025-02-17 20:26:28,769][flwr][INFO] - aggregate_fit: received 49 results and 1 failures
[2025-02-17 20:26:33,262][flwr][INFO] - fit progress: (10, 0.03411157367825508, {'accuracy': 0.6769}, 704.4248406859988)
[2025-02-17 20:26:33,262][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 20:26:48,796][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 20:26:48,797][flwr][INFO] - 
[2025-02-17 20:26:48,797][flwr][INFO] - [ROUND 11]
[2025-02-17 20:26:48,797][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 20:27:25,990][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-17 20:27:30,377][flwr][INFO] - fit progress: (11, 0.038220805776119235, {'accuracy': 0.6846}, 761.5397352050059)
[2025-02-17 20:27:30,377][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 20:27:46,235][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 20:27:46,235][flwr][INFO] - 
[2025-02-17 20:27:46,235][flwr][INFO] - [ROUND 12]
[2025-02-17 20:27:46,235][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 20:28:23,959][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-17 20:28:28,415][flwr][INFO] - fit progress: (12, 0.045358906561136246, {'accuracy': 0.684}, 819.5779773569957)
[2025-02-17 20:28:28,415][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 20:28:43,876][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 20:28:43,876][flwr][INFO] - 
[2025-02-17 20:28:43,876][flwr][INFO] - [ROUND 13]
[2025-02-17 20:28:43,877][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 20:29:20,191][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-17 20:29:24,714][flwr][INFO] - fit progress: (13, 0.0557630897462368, {'accuracy': 0.6783}, 875.8769302100118)
[2025-02-17 20:29:24,714][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 20:29:40,012][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 20:29:40,012][flwr][INFO] - 
[2025-02-17 20:29:40,013][flwr][INFO] - [ROUND 14]
[2025-02-17 20:29:40,013][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 20:30:17,252][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-17 20:30:21,715][flwr][INFO] - fit progress: (14, 0.06965450183451176, {'accuracy': 0.6685}, 932.8783232599963)
[2025-02-17 20:30:21,716][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 20:30:37,471][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 20:30:37,471][flwr][INFO] - 
[2025-02-17 20:30:37,472][flwr][INFO] - [ROUND 15]
[2025-02-17 20:30:37,472][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 20:31:15,306][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-17 20:31:19,744][flwr][INFO] - fit progress: (15, 0.08768969367444515, {'accuracy': 0.6564}, 990.9074636790028)
[2025-02-17 20:31:19,745][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 20:31:37,431][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 20:31:37,432][flwr][INFO] - 
[2025-02-17 20:31:37,432][flwr][INFO] - [ROUND 16]
[2025-02-17 20:31:37,432][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 20:32:14,868][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-17 20:32:19,132][flwr][INFO] - fit progress: (16, 0.11063376064300537, {'accuracy': 0.6406}, 1050.2952680060116)
[2025-02-17 20:32:19,132][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 20:32:34,262][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 20:32:34,263][flwr][INFO] - 
[2025-02-17 20:32:34,263][flwr][INFO] - [ROUND 17]
[2025-02-17 20:32:34,263][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 20:33:12,994][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-17 20:33:17,153][flwr][INFO] - fit progress: (17, 0.13964686862826348, {'accuracy': 0.6262}, 1108.3162862980098)
[2025-02-17 20:33:17,154][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 20:33:33,634][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 20:33:33,635][flwr][INFO] - 
[2025-02-17 20:33:33,635][flwr][INFO] - [ROUND 18]
[2025-02-17 20:33:33,635][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 20:34:11,272][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-17 20:34:15,433][flwr][INFO] - fit progress: (18, 0.17523593645095825, {'accuracy': 0.6114}, 1166.5958626840147)
[2025-02-17 20:34:15,433][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 20:34:30,988][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 20:34:30,988][flwr][INFO] - 
[2025-02-17 20:34:30,988][flwr][INFO] - [ROUND 19]
[2025-02-17 20:34:30,989][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 20:35:08,321][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-17 20:35:12,883][flwr][INFO] - fit progress: (19, 0.2188247924208641, {'accuracy': 0.5979}, 1224.0462180600152)
[2025-02-17 20:35:12,883][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 20:35:28,742][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 20:35:28,743][flwr][INFO] - 
[2025-02-17 20:35:28,743][flwr][INFO] - [ROUND 20]
[2025-02-17 20:35:28,743][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 20:36:05,370][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-17 20:36:09,537][flwr][INFO] - fit progress: (20, 0.2719212434768677, {'accuracy': 0.5819}, 1280.6995455769938)
[2025-02-17 20:36:09,537][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 20:36:28,192][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 20:36:28,193][flwr][INFO] - 
[2025-02-17 20:36:28,193][flwr][INFO] - [SUMMARY]
[2025-02-17 20:36:28,193][flwr][INFO] - Run finished 20 round(s) in 1299.36s
[2025-02-17 20:36:28,194][flwr][INFO] - 	History (loss, distributed):
[2025-02-17 20:36:28,194][flwr][INFO] - 		round 1: 0.07649134695529941
[2025-02-17 20:36:28,194][flwr][INFO] - 		round 2: 0.07594262782732644
[2025-02-17 20:36:28,194][flwr][INFO] - 		round 3: 0.07458578952153525
[2025-02-17 20:36:28,194][flwr][INFO] - 		round 4: 0.07142343024412791
[2025-02-17 20:36:28,194][flwr][INFO] - 		round 5: 0.06561035680770874
[2025-02-17 20:36:28,194][flwr][INFO] - 		round 6: 0.056676607767740875
[2025-02-17 20:36:28,195][flwr][INFO] - 		round 7: 0.046786081612110134
[2025-02-17 20:36:28,195][flwr][INFO] - 		round 8: 0.039657743702332174
[2025-02-17 20:36:28,195][flwr][INFO] - 		round 9: 0.037156849622726446
[2025-02-17 20:36:28,195][flwr][INFO] - 		round 10: 0.03889529683689276
[2025-02-17 20:36:28,195][flwr][INFO] - 		round 11: 0.043800355200966194
[2025-02-17 20:36:28,195][flwr][INFO] - 		round 12: 0.052104111010829623
[2025-02-17 20:36:28,195][flwr][INFO] - 		round 13: 0.06406020856897038
[2025-02-17 20:36:28,195][flwr][INFO] - 		round 14: 0.07985577978690464
[2025-02-17 20:36:28,195][flwr][INFO] - 		round 15: 0.10038741602500281
[2025-02-17 20:36:28,195][flwr][INFO] - 		round 16: 0.12624229179819427
[2025-02-17 20:36:28,195][flwr][INFO] - 		round 17: 0.15870923880736035
[2025-02-17 20:36:28,195][flwr][INFO] - 		round 18: 0.1984318022727966
[2025-02-17 20:36:28,196][flwr][INFO] - 		round 19: 0.24687468155225126
[2025-02-17 20:36:28,196][flwr][INFO] - 		round 20: 0.305513813773791
[2025-02-17 20:36:28,196][flwr][INFO] - 	History (loss, centralized):
[2025-02-17 20:36:28,196][flwr][INFO] - 		round 0: 0.07214015040397644
[2025-02-17 20:36:28,196][flwr][INFO] - 		round 1: 0.0718349406003952
[2025-02-17 20:36:28,196][flwr][INFO] - 		round 2: 0.07129651372432709
[2025-02-17 20:36:28,196][flwr][INFO] - 		round 3: 0.0699718425989151
[2025-02-17 20:36:28,196][flwr][INFO] - 		round 4: 0.06690800302028656
[2025-02-17 20:36:28,196][flwr][INFO] - 		round 5: 0.06129104617834091
[2025-02-17 20:36:28,196][flwr][INFO] - 		round 6: 0.05262519137859344
[2025-02-17 20:36:28,196][flwr][INFO] - 		round 7: 0.04293306818008423
[2025-02-17 20:36:28,197][flwr][INFO] - 		round 8: 0.03583903885483742
[2025-02-17 20:36:28,197][flwr][INFO] - 		round 9: 0.033026599270105365
[2025-02-17 20:36:28,197][flwr][INFO] - 		round 10: 0.03411157367825508
[2025-02-17 20:36:28,197][flwr][INFO] - 		round 11: 0.038220805776119235
[2025-02-17 20:36:28,197][flwr][INFO] - 		round 12: 0.045358906561136246
[2025-02-17 20:36:28,197][flwr][INFO] - 		round 13: 0.0557630897462368
[2025-02-17 20:36:28,197][flwr][INFO] - 		round 14: 0.06965450183451176
[2025-02-17 20:36:28,197][flwr][INFO] - 		round 15: 0.08768969367444515
[2025-02-17 20:36:28,197][flwr][INFO] - 		round 16: 0.11063376064300537
[2025-02-17 20:36:28,197][flwr][INFO] - 		round 17: 0.13964686862826348
[2025-02-17 20:36:28,197][flwr][INFO] - 		round 18: 0.17523593645095825
[2025-02-17 20:36:28,197][flwr][INFO] - 		round 19: 0.2188247924208641
[2025-02-17 20:36:28,198][flwr][INFO] - 		round 20: 0.2719212434768677
[2025-02-17 20:36:28,198][flwr][INFO] - 	History (metrics, distributed, fit):
[2025-02-17 20:36:28,198][flwr][INFO] - 	{'clients_epsilons': [(1, 1.0),
[2025-02-17 20:36:28,198][flwr][INFO] - 	                      (2, 1.0),
[2025-02-17 20:36:28,198][flwr][INFO] - 	                      (3, 1.0),
[2025-02-17 20:36:28,198][flwr][INFO] - 	                      (4, 1.0),
[2025-02-17 20:36:28,198][flwr][INFO] - 	                      (5, 1.0),
[2025-02-17 20:36:28,198][flwr][INFO] - 	                      (6, 1.0),
[2025-02-17 20:36:28,198][flwr][INFO] - 	                      (7, 1.0),
[2025-02-17 20:36:28,198][flwr][INFO] - 	                      (8, 1.0),
[2025-02-17 20:36:28,198][flwr][INFO] - 	                      (9, 1.0),
[2025-02-17 20:36:28,198][flwr][INFO] - 	                      (10, 1.0),
[2025-02-17 20:36:28,199][flwr][INFO] - 	                      (11, 1.0),
[2025-02-17 20:36:28,199][flwr][INFO] - 	                      (12, 1.0),
[2025-02-17 20:36:28,199][flwr][INFO] - 	                      (13, 1.0),
[2025-02-17 20:36:28,199][flwr][INFO] - 	                      (14, 1.0),
[2025-02-17 20:36:28,199][flwr][INFO] - 	                      (15, 1.0),
[2025-02-17 20:36:28,199][flwr][INFO] - 	                      (16, 1.0),
[2025-02-17 20:36:28,199][flwr][INFO] - 	                      (17, 1.0),
[2025-02-17 20:36:28,199][flwr][INFO] - 	                      (18, 1.0),
[2025-02-17 20:36:28,199][flwr][INFO] - 	                      (19, 1.0),
[2025-02-17 20:36:28,199][flwr][INFO] - 	                      (20, 1.0)],
[2025-02-17 20:36:28,199][flwr][INFO] - 	 'clients_losses': [(1, 2.3005800940195718),
[2025-02-17 20:36:28,199][flwr][INFO] - 	                    (2, 2.2884341665903727),
[2025-02-17 20:36:28,200][flwr][INFO] - 	                    (3, 2.264225770632426),
[2025-02-17 20:36:28,200][flwr][INFO] - 	                    (4, 2.2045810801188153),
[2025-02-17 20:36:28,200][flwr][INFO] - 	                    (5, 2.08232819881845),
[2025-02-17 20:36:28,200][flwr][INFO] - 	                    (6, 1.8763673850695293),
[2025-02-17 20:36:28,200][flwr][INFO] - 	                    (7, 1.5967707142829894),
[2025-02-17 20:36:28,200][flwr][INFO] - 	                    (8, 1.3327453032334646),
[2025-02-17 20:36:28,200][flwr][INFO] - 	                    (9, 1.179634915192922),
[2025-02-17 20:36:28,200][flwr][INFO] - 	                    (10, 1.1624603814413759),
[2025-02-17 20:36:28,200][flwr][INFO] - 	                    (11, 1.2624210251569747),
[2025-02-17 20:36:28,200][flwr][INFO] - 	                    (12, 1.4552774879137675),
[2025-02-17 20:36:28,200][flwr][INFO] - 	                    (13, 1.7501144660512606),
[2025-02-17 20:36:28,200][flwr][INFO] - 	                    (14, 2.1541466015179953),
[2025-02-17 20:36:28,201][flwr][INFO] - 	                    (15, 2.6854193224112195),
[2025-02-17 20:36:28,201][flwr][INFO] - 	                    (16, 3.3567126702467602),
[2025-02-17 20:36:28,201][flwr][INFO] - 	                    (17, 4.2031661474704745),
[2025-02-17 20:36:28,201][flwr][INFO] - 	                    (18, 5.25967133140564),
[2025-02-17 20:36:28,201][flwr][INFO] - 	                    (19, 6.557043422222137),
[2025-02-17 20:36:28,201][flwr][INFO] - 	                    (20, 8.135362194538116)]}
[2025-02-17 20:36:28,201][flwr][INFO] - 	History (metrics, distributed, evaluate):
[2025-02-17 20:36:28,201][flwr][INFO] - 	{'clients_accuracies': [(1, 0.1446666666666667),
[2025-02-17 20:36:28,201][flwr][INFO] - 	                        (2, 0.12999999999999998),
[2025-02-17 20:36:28,201][flwr][INFO] - 	                        (3, 0.3065),
[2025-02-17 20:36:28,201][flwr][INFO] - 	                        (4, 0.40049999999999986),
[2025-02-17 20:36:28,202][flwr][INFO] - 	                        (5, 0.468),
[2025-02-17 20:36:28,202][flwr][INFO] - 	                        (6, 0.5281666666666667),
[2025-02-17 20:36:28,202][flwr][INFO] - 	                        (7, 0.5934999999999999),
[2025-02-17 20:36:28,202][flwr][INFO] - 	                        (8, 0.6308333333333332),
[2025-02-17 20:36:28,202][flwr][INFO] - 	                        (9, 0.6510000000000001),
[2025-02-17 20:36:28,202][flwr][INFO] - 	                        (10, 0.6618333333333334),
[2025-02-17 20:36:28,202][flwr][INFO] - 	                        (11, 0.6691666666666669),
[2025-02-17 20:36:28,202][flwr][INFO] - 	                        (12, 0.6678333333333335),
[2025-02-17 20:36:28,202][flwr][INFO] - 	                        (13, 0.6603333333333333),
[2025-02-17 20:36:28,202][flwr][INFO] - 	                        (14, 0.6516666666666668),
[2025-02-17 20:36:28,202][flwr][INFO] - 	                        (15, 0.6361666666666665),
[2025-02-17 20:36:28,202][flwr][INFO] - 	                        (16, 0.6168333333333333),
[2025-02-17 20:36:28,202][flwr][INFO] - 	                        (17, 0.6025),
[2025-02-17 20:36:28,203][flwr][INFO] - 	                        (18, 0.5928333333333332),
[2025-02-17 20:36:28,203][flwr][INFO] - 	                        (19, 0.5795),
[2025-02-17 20:36:28,203][flwr][INFO] - 	                        (20, 0.5666666666666667)],
[2025-02-17 20:36:28,203][flwr][INFO] - 	 'clients_losses': [(1, 0.07649134695529941),
[2025-02-17 20:36:28,203][flwr][INFO] - 	                    (2, 0.07594262782732644),
[2025-02-17 20:36:28,203][flwr][INFO] - 	                    (3, 0.07458578952153525),
[2025-02-17 20:36:28,203][flwr][INFO] - 	                    (4, 0.07142343024412791),
[2025-02-17 20:36:28,203][flwr][INFO] - 	                    (5, 0.06561035680770874),
[2025-02-17 20:36:28,203][flwr][INFO] - 	                    (6, 0.056676607767740875),
[2025-02-17 20:36:28,203][flwr][INFO] - 	                    (7, 0.046786081612110134),
[2025-02-17 20:36:28,203][flwr][INFO] - 	                    (8, 0.039657743702332174),
[2025-02-17 20:36:28,203][flwr][INFO] - 	                    (9, 0.037156849622726446),
[2025-02-17 20:36:28,204][flwr][INFO] - 	                    (10, 0.03889529683689276),
[2025-02-17 20:36:28,204][flwr][INFO] - 	                    (11, 0.043800355200966194),
[2025-02-17 20:36:28,204][flwr][INFO] - 	                    (12, 0.052104111010829623),
[2025-02-17 20:36:28,204][flwr][INFO] - 	                    (13, 0.06406020856897038),
[2025-02-17 20:36:28,204][flwr][INFO] - 	                    (14, 0.07985577978690464),
[2025-02-17 20:36:28,204][flwr][INFO] - 	                    (15, 0.10038741602500281),
[2025-02-17 20:36:28,204][flwr][INFO] - 	                    (16, 0.12624229179819427),
[2025-02-17 20:36:28,204][flwr][INFO] - 	                    (17, 0.15870923880736035),
[2025-02-17 20:36:28,204][flwr][INFO] - 	                    (18, 0.1984318022727966),
[2025-02-17 20:36:28,204][flwr][INFO] - 	                    (19, 0.24687468155225126),
[2025-02-17 20:36:28,204][flwr][INFO] - 	                    (20, 0.305513813773791)]}
[2025-02-17 20:36:28,204][flwr][INFO] - 	History (metrics, centralized):
[2025-02-17 20:36:28,205][flwr][INFO] - 	{'accuracy': [(0, 0.0988),
[2025-02-17 20:36:28,205][flwr][INFO] - 	              (1, 0.1395),
[2025-02-17 20:36:28,205][flwr][INFO] - 	              (2, 0.1279),
[2025-02-17 20:36:28,205][flwr][INFO] - 	              (3, 0.3108),
[2025-02-17 20:36:28,205][flwr][INFO] - 	              (4, 0.4077),
[2025-02-17 20:36:28,205][flwr][INFO] - 	              (5, 0.4755),
[2025-02-17 20:36:28,205][flwr][INFO] - 	              (6, 0.5422),
[2025-02-17 20:36:28,205][flwr][INFO] - 	              (7, 0.6093),
[2025-02-17 20:36:28,205][flwr][INFO] - 	              (8, 0.6433),
[2025-02-17 20:36:28,206][flwr][INFO] - 	              (9, 0.666),
[2025-02-17 20:36:28,206][flwr][INFO] - 	              (10, 0.6769),
[2025-02-17 20:36:28,206][flwr][INFO] - 	              (11, 0.6846),
[2025-02-17 20:36:28,206][flwr][INFO] - 	              (12, 0.684),
[2025-02-17 20:36:28,206][flwr][INFO] - 	              (13, 0.6783),
[2025-02-17 20:36:28,206][flwr][INFO] - 	              (14, 0.6685),
[2025-02-17 20:36:28,206][flwr][INFO] - 	              (15, 0.6564),
[2025-02-17 20:36:28,206][flwr][INFO] - 	              (16, 0.6406),
[2025-02-17 20:36:28,206][flwr][INFO] - 	              (17, 0.6262),
[2025-02-17 20:36:28,206][flwr][INFO] - 	              (18, 0.6114),
[2025-02-17 20:36:28,206][flwr][INFO] - 	              (19, 0.5979),
[2025-02-17 20:36:28,207][flwr][INFO] - 	              (20, 0.5819)]}
[2025-02-17 20:36:28,207][flwr][INFO] - 
