[2025-02-17 17:42:02,253][flwr][INFO] - Starting Flower ServerApp, config: num_rounds=20, no round_timeout
[2025-02-17 17:42:02,254][flwr][INFO] - 
[2025-02-17 17:42:02,255][flwr][INFO] - [INIT]
[2025-02-17 17:42:02,256][flwr][INFO] - Using initial global parameters provided by strategy
[2025-02-17 17:42:02,257][flwr][INFO] - Starting evaluation of initial global parameters
[2025-02-17 17:42:08,873][flwr][INFO] - initial parameters (loss, other metrics): 0.07212486484050751, {'accuracy': 0.0958}
[2025-02-17 17:42:08,873][flwr][INFO] - 
[2025-02-17 17:42:08,873][flwr][INFO] - [ROUND 1]
[2025-02-17 17:42:08,873][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:42:20,600][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 17:42:25,182][flwr][INFO] - fit progress: (1, 0.07141710765361786, {'accuracy': 0.1288}, 16.309197239985224)
[2025-02-17 17:42:25,183][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:42:31,395][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 17:42:31,396][flwr][INFO] - 
[2025-02-17 17:42:31,396][flwr][INFO] - [ROUND 2]
[2025-02-17 17:42:31,396][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:42:39,010][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 17:42:43,655][flwr][INFO] - fit progress: (2, 0.07069997837543487, {'accuracy': 0.1495}, 34.7819553159934)
[2025-02-17 17:42:43,655][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:42:49,165][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 17:42:49,165][flwr][INFO] - 
[2025-02-17 17:42:49,165][flwr][INFO] - [ROUND 3]
[2025-02-17 17:42:49,166][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:42:55,979][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 17:43:00,437][flwr][INFO] - fit progress: (3, 0.06888580822944641, {'accuracy': 0.1659}, 51.56367692200001)
[2025-02-17 17:43:00,437][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:43:05,246][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 17:43:05,246][flwr][INFO] - 
[2025-02-17 17:43:05,246][flwr][INFO] - [ROUND 4]
[2025-02-17 17:43:05,246][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:43:12,458][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 17:43:17,112][flwr][INFO] - fit progress: (4, 0.0645026317000389, {'accuracy': 0.3314}, 68.23905568398186)
[2025-02-17 17:43:17,112][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:43:21,122][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 17:43:21,123][flwr][INFO] - 
[2025-02-17 17:43:21,123][flwr][INFO] - [ROUND 5]
[2025-02-17 17:43:21,123][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:43:28,235][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 17:43:33,259][flwr][INFO] - fit progress: (5, 0.05883583195209503, {'accuracy': 0.4105}, 84.3854878830025)
[2025-02-17 17:43:33,259][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:43:37,568][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 17:43:37,569][flwr][INFO] - 
[2025-02-17 17:43:37,569][flwr][INFO] - [ROUND 6]
[2025-02-17 17:43:37,569][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:45:42,860][flwr][ERROR] - An exception was raised when processing a message by RayBackend
[2025-02-17 17:45:42,860][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=18333, ip=172.27.85.201, actor_id=41f74f71596c67467e55823701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9b8432aed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=18333, ip=172.27.85.201, actor_id=41f74f71596c67467e55823701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9b8432aed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=18333, ip=172.27.85.201, actor_id=41f74f71596c67467e55823701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9b8432aed0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c
[2025-02-17 17:45:42,862][flwr][ERROR] - Traceback (most recent call last):
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py", line 112, in worker
    out_mssg, updated_context = backend.process_message(message, context)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 187, in process_message
    raise ex
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 175, in process_message
    ) = self.pool.fetch_result_and_return_actor_to_pool(future)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 478, in fetch_result_and_return_actor_to_pool
    _, out_mssg, updated_context = ray.get(future)
                                   ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=18333, ip=172.27.85.201, actor_id=41f74f71596c67467e55823701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9b8432aed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=18333, ip=172.27.85.201, actor_id=41f74f71596c67467e55823701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9b8432aed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=18333, ip=172.27.85.201, actor_id=41f74f71596c67467e55823701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9b8432aed0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

[2025-02-17 17:45:42,959][flwr][INFO] - aggregate_fit: received 9 results and 1 failures
[2025-02-17 17:45:47,536][flwr][INFO] - fit progress: (6, 0.05701416698694229, {'accuracy': 0.4459}, 218.66277469700435)
[2025-02-17 17:45:47,536][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:45:52,046][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 17:45:52,047][flwr][INFO] - 
[2025-02-17 17:45:52,047][flwr][INFO] - [ROUND 7]
[2025-02-17 17:45:52,047][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:46:01,967][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 17:46:06,557][flwr][INFO] - fit progress: (7, 0.06749344198703766, {'accuracy': 0.4714}, 237.6840994869999)
[2025-02-17 17:46:06,558][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:46:12,170][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 17:46:12,171][flwr][INFO] - 
[2025-02-17 17:46:12,171][flwr][INFO] - [ROUND 8]
[2025-02-17 17:46:12,171][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:46:19,188][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 17:46:24,018][flwr][INFO] - fit progress: (8, 0.09065942995548248, {'accuracy': 0.4742}, 255.14463122800225)
[2025-02-17 17:46:24,018][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:46:37,853][flwr][ERROR] - An exception was raised when processing a message by RayBackend
[2025-02-17 17:46:37,853][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=18337, ip=172.27.85.201, actor_id=f0a78625dbd9da82c7baff0f01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f66641fb2d0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=18337, ip=172.27.85.201, actor_id=f0a78625dbd9da82c7baff0f01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f66641fb2d0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=18337, ip=172.27.85.201, actor_id=f0a78625dbd9da82c7baff0f01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f66641fb2d0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c
[2025-02-17 17:46:37,854][flwr][ERROR] - Traceback (most recent call last):
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py", line 112, in worker
    out_mssg, updated_context = backend.process_message(message, context)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 187, in process_message
    raise ex
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 175, in process_message
    ) = self.pool.fetch_result_and_return_actor_to_pool(future)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 478, in fetch_result_and_return_actor_to_pool
    _, out_mssg, updated_context = ray.get(future)
                                   ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=18337, ip=172.27.85.201, actor_id=f0a78625dbd9da82c7baff0f01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f66641fb2d0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=18337, ip=172.27.85.201, actor_id=f0a78625dbd9da82c7baff0f01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f66641fb2d0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=18337, ip=172.27.85.201, actor_id=f0a78625dbd9da82c7baff0f01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f66641fb2d0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

[2025-02-17 17:46:47,823][flwr][ERROR] - An exception was raised when processing a message by RayBackend
[2025-02-17 17:46:47,823][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=18340, ip=172.27.85.201, actor_id=2c1b3dc046a513b8a9f36e7c01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f4e20217b90>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=18340, ip=172.27.85.201, actor_id=2c1b3dc046a513b8a9f36e7c01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f4e20217b90>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=18340, ip=172.27.85.201, actor_id=2c1b3dc046a513b8a9f36e7c01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f4e20217b90>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c
[2025-02-17 17:46:47,824][flwr][ERROR] - Traceback (most recent call last):
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py", line 112, in worker
    out_mssg, updated_context = backend.process_message(message, context)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 187, in process_message
    raise ex
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 175, in process_message
    ) = self.pool.fetch_result_and_return_actor_to_pool(future)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 478, in fetch_result_and_return_actor_to_pool
    _, out_mssg, updated_context = ray.get(future)
                                   ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=18340, ip=172.27.85.201, actor_id=2c1b3dc046a513b8a9f36e7c01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f4e20217b90>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=18340, ip=172.27.85.201, actor_id=2c1b3dc046a513b8a9f36e7c01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f4e20217b90>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=18340, ip=172.27.85.201, actor_id=2c1b3dc046a513b8a9f36e7c01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f4e20217b90>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

[2025-02-17 17:46:47,854][flwr][INFO] - aggregate_evaluate: received 8 results and 2 failures
[2025-02-17 17:46:47,854][flwr][INFO] - 
[2025-02-17 17:46:47,854][flwr][INFO] - [ROUND 9]
[2025-02-17 17:46:47,854][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:47:02,249][flwr][ERROR] - An exception was raised when processing a message by RayBackend
[2025-02-17 17:47:02,249][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=18338, ip=172.27.85.201, actor_id=b8b52ad6e3838dfea5c182e501000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f6e584b6ed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=18338, ip=172.27.85.201, actor_id=b8b52ad6e3838dfea5c182e501000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f6e584b6ed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=18338, ip=172.27.85.201, actor_id=b8b52ad6e3838dfea5c182e501000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f6e584b6ed0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c
[2025-02-17 17:47:02,250][flwr][ERROR] - Traceback (most recent call last):
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py", line 112, in worker
    out_mssg, updated_context = backend.process_message(message, context)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 187, in process_message
    raise ex
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 175, in process_message
    ) = self.pool.fetch_result_and_return_actor_to_pool(future)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 478, in fetch_result_and_return_actor_to_pool
    _, out_mssg, updated_context = ray.get(future)
                                   ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=18338, ip=172.27.85.201, actor_id=b8b52ad6e3838dfea5c182e501000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f6e584b6ed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=18338, ip=172.27.85.201, actor_id=b8b52ad6e3838dfea5c182e501000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f6e584b6ed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=18338, ip=172.27.85.201, actor_id=b8b52ad6e3838dfea5c182e501000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f6e584b6ed0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

[2025-02-17 17:47:04,982][flwr][INFO] - aggregate_fit: received 9 results and 1 failures
[2025-02-17 17:47:10,183][flwr][INFO] - fit progress: (9, 0.1312714908719063, {'accuracy': 0.4693}, 301.3094545339991)
[2025-02-17 17:47:10,183][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:47:14,694][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 17:47:14,695][flwr][INFO] - 
[2025-02-17 17:47:14,695][flwr][INFO] - [ROUND 10]
[2025-02-17 17:47:14,695][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:47:21,514][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 17:47:26,002][flwr][INFO] - fit progress: (10, 0.19341270122528076, {'accuracy': 0.4568}, 317.1287722249981)
[2025-02-17 17:47:26,002][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:47:30,412][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 17:47:30,413][flwr][INFO] - 
[2025-02-17 17:47:30,413][flwr][INFO] - [ROUND 11]
[2025-02-17 17:47:30,413][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:47:37,827][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 17:47:42,178][flwr][INFO] - fit progress: (11, 0.2846946757078171, {'accuracy': 0.4362}, 333.30454753898084)
[2025-02-17 17:47:42,178][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:47:46,587][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 17:47:46,588][flwr][INFO] - 
[2025-02-17 17:47:46,588][flwr][INFO] - [ROUND 12]
[2025-02-17 17:47:46,588][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:47:53,603][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 17:47:58,168][flwr][INFO] - fit progress: (12, 0.4109651708126068, {'accuracy': 0.4155}, 349.29459711399977)
[2025-02-17 17:47:58,168][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:48:02,377][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 17:48:02,377][flwr][INFO] - 
[2025-02-17 17:48:02,377][flwr][INFO] - [ROUND 13]
[2025-02-17 17:48:02,377][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:48:09,291][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 17:48:13,688][flwr][INFO] - fit progress: (13, 0.5826278513908386, {'accuracy': 0.3999}, 364.8147561539954)
[2025-02-17 17:48:13,688][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:48:18,199][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 17:48:18,199][flwr][INFO] - 
[2025-02-17 17:48:18,199][flwr][INFO] - [ROUND 14]
[2025-02-17 17:48:18,200][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:48:25,014][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 17:48:29,330][flwr][INFO] - fit progress: (14, 0.8093786109924317, {'accuracy': 0.3845}, 380.4569109909935)
[2025-02-17 17:48:29,330][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:48:34,540][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 17:48:34,541][flwr][INFO] - 
[2025-02-17 17:48:34,541][flwr][INFO] - [ROUND 15]
[2025-02-17 17:48:34,541][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:48:41,653][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 17:48:46,490][flwr][INFO] - fit progress: (15, 1.1057673892974853, {'accuracy': 0.3703}, 397.6170134949789)
[2025-02-17 17:48:46,490][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:48:51,700][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 17:48:51,701][flwr][INFO] - 
[2025-02-17 17:48:51,701][flwr][INFO] - [ROUND 16]
[2025-02-17 17:48:51,701][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:48:58,616][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 17:49:03,586][flwr][INFO] - fit progress: (16, 1.4812518983840943, {'accuracy': 0.3586}, 414.71254236399545)
[2025-02-17 17:49:03,586][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:49:08,898][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 17:49:08,899][flwr][INFO] - 
[2025-02-17 17:49:08,899][flwr][INFO] - [ROUND 17]
[2025-02-17 17:49:08,899][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:49:15,515][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 17:49:20,275][flwr][INFO] - fit progress: (17, 1.951025846862793, {'accuracy': 0.3478}, 431.4017045070068)
[2025-02-17 17:49:20,275][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:49:24,484][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 17:49:24,485][flwr][INFO] - 
[2025-02-17 17:49:24,485][flwr][INFO] - [ROUND 18]
[2025-02-17 17:49:24,485][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:49:31,200][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 17:49:35,752][flwr][INFO] - fit progress: (18, 2.5337993221282957, {'accuracy': 0.3386}, 446.87862446098006)
[2025-02-17 17:49:35,752][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:49:40,269][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 17:49:40,270][flwr][INFO] - 
[2025-02-17 17:49:40,270][flwr][INFO] - [ROUND 19]
[2025-02-17 17:49:40,270][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:49:48,085][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 17:49:52,611][flwr][INFO] - fit progress: (19, 3.2470529624938966, {'accuracy': 0.333}, 463.7375440179894)
[2025-02-17 17:49:52,611][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:49:56,823][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 17:49:56,823][flwr][INFO] - 
[2025-02-17 17:49:56,823][flwr][INFO] - [ROUND 20]
[2025-02-17 17:49:56,824][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-17 17:50:03,538][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-17 17:50:07,816][flwr][INFO] - fit progress: (20, 4.106500824737549, {'accuracy': 0.3298}, 478.94269865198294)
[2025-02-17 17:50:07,816][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-17 17:50:12,025][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-17 17:50:12,026][flwr][INFO] - 
[2025-02-17 17:50:12,026][flwr][INFO] - [SUMMARY]
[2025-02-17 17:50:12,026][flwr][INFO] - Run finished 20 round(s) in 483.15s
[2025-02-17 17:50:12,027][flwr][INFO] - 	History (loss, distributed):
[2025-02-17 17:50:12,027][flwr][INFO] - 		round 1: 0.07607730786005655
[2025-02-17 17:50:12,027][flwr][INFO] - 		round 2: 0.07533424019813538
[2025-02-17 17:50:12,027][flwr][INFO] - 		round 3: 0.07350963393847147
[2025-02-17 17:50:12,027][flwr][INFO] - 		round 4: 0.06918202410141627
[2025-02-17 17:50:12,027][flwr][INFO] - 		round 5: 0.06399892777204515
[2025-02-17 17:50:12,027][flwr][INFO] - 		round 6: 0.06308051556348801
[2025-02-17 17:50:12,027][flwr][INFO] - 		round 7: 0.0761088451743126
[2025-02-17 17:50:12,027][flwr][INFO] - 		round 8: 0.10416750013828278
[2025-02-17 17:50:12,027][flwr][INFO] - 		round 9: 0.14949003239472708
[2025-02-17 17:50:12,028][flwr][INFO] - 		round 10: 0.2191708385944367
[2025-02-17 17:50:12,028][flwr][INFO] - 		round 11: 0.32210256973902385
[2025-02-17 17:50:12,028][flwr][INFO] - 		round 12: 0.46376338203748063
[2025-02-17 17:50:12,028][flwr][INFO] - 		round 13: 0.6572337683041891
[2025-02-17 17:50:12,028][flwr][INFO] - 		round 14: 0.9145108207066854
[2025-02-17 17:50:12,028][flwr][INFO] - 		round 15: 1.2540117454528807
[2025-02-17 17:50:12,028][flwr][INFO] - 		round 16: 1.6810016345977783
[2025-02-17 17:50:12,028][flwr][INFO] - 		round 17: 2.2102743117014567
[2025-02-17 17:50:12,028][flwr][INFO] - 		round 18: 2.866259644826253
[2025-02-17 17:50:12,028][flwr][INFO] - 		round 19: 3.6701636028289792
[2025-02-17 17:50:12,028][flwr][INFO] - 		round 20: 4.640328458150228
[2025-02-17 17:50:12,028][flwr][INFO] - 	History (loss, centralized):
[2025-02-17 17:50:12,029][flwr][INFO] - 		round 0: 0.07212486484050751
[2025-02-17 17:50:12,029][flwr][INFO] - 		round 1: 0.07141710765361786
[2025-02-17 17:50:12,029][flwr][INFO] - 		round 2: 0.07069997837543487
[2025-02-17 17:50:12,029][flwr][INFO] - 		round 3: 0.06888580822944641
[2025-02-17 17:50:12,029][flwr][INFO] - 		round 4: 0.0645026317000389
[2025-02-17 17:50:12,029][flwr][INFO] - 		round 5: 0.05883583195209503
[2025-02-17 17:50:12,029][flwr][INFO] - 		round 6: 0.05701416698694229
[2025-02-17 17:50:12,029][flwr][INFO] - 		round 7: 0.06749344198703766
[2025-02-17 17:50:12,029][flwr][INFO] - 		round 8: 0.09065942995548248
[2025-02-17 17:50:12,029][flwr][INFO] - 		round 9: 0.1312714908719063
[2025-02-17 17:50:12,029][flwr][INFO] - 		round 10: 0.19341270122528076
[2025-02-17 17:50:12,030][flwr][INFO] - 		round 11: 0.2846946757078171
[2025-02-17 17:50:12,030][flwr][INFO] - 		round 12: 0.4109651708126068
[2025-02-17 17:50:12,030][flwr][INFO] - 		round 13: 0.5826278513908386
[2025-02-17 17:50:12,030][flwr][INFO] - 		round 14: 0.8093786109924317
[2025-02-17 17:50:12,030][flwr][INFO] - 		round 15: 1.1057673892974853
[2025-02-17 17:50:12,030][flwr][INFO] - 		round 16: 1.4812518983840943
[2025-02-17 17:50:12,030][flwr][INFO] - 		round 17: 1.951025846862793
[2025-02-17 17:50:12,030][flwr][INFO] - 		round 18: 2.5337993221282957
[2025-02-17 17:50:12,030][flwr][INFO] - 		round 19: 3.2470529624938966
[2025-02-17 17:50:12,030][flwr][INFO] - 		round 20: 4.106500824737549
[2025-02-17 17:50:12,030][flwr][INFO] - 	History (metrics, distributed, fit):
[2025-02-17 17:50:12,030][flwr][INFO] - 	{'clients_epsilons': [(1, 1.0),
[2025-02-17 17:50:12,030][flwr][INFO] - 	                      (2, 1.0),
[2025-02-17 17:50:12,031][flwr][INFO] - 	                      (3, 1.0),
[2025-02-17 17:50:12,031][flwr][INFO] - 	                      (4, 1.0),
[2025-02-17 17:50:12,031][flwr][INFO] - 	                      (5, 1.0),
[2025-02-17 17:50:12,031][flwr][INFO] - 	                      (6, 1.0),
[2025-02-17 17:50:12,031][flwr][INFO] - 	                      (7, 1.0),
[2025-02-17 17:50:12,031][flwr][INFO] - 	                      (8, 1.0),
[2025-02-17 17:50:12,031][flwr][INFO] - 	                      (9, 1.0),
[2025-02-17 17:50:12,031][flwr][INFO] - 	                      (10, 1.0),
[2025-02-17 17:50:12,031][flwr][INFO] - 	                      (11, 1.0),
[2025-02-17 17:50:12,031][flwr][INFO] - 	                      (12, 1.0),
[2025-02-17 17:50:12,031][flwr][INFO] - 	                      (13, 1.0),
[2025-02-17 17:50:12,031][flwr][INFO] - 	                      (14, 1.0),
[2025-02-17 17:50:12,031][flwr][INFO] - 	                      (15, 1.0),
[2025-02-17 17:50:12,032][flwr][INFO] - 	                      (16, 1.0),
[2025-02-17 17:50:12,032][flwr][INFO] - 	                      (17, 1.0),
[2025-02-17 17:50:12,032][flwr][INFO] - 	                      (18, 1.0),
[2025-02-17 17:50:12,032][flwr][INFO] - 	                      (19, 1.0),
[2025-02-17 17:50:12,032][flwr][INFO] - 	                      (20, 1.0)],
[2025-02-17 17:50:12,032][flwr][INFO] - 	 'clients_losses': [(1, 2.2904450448354083),
[2025-02-17 17:50:12,032][flwr][INFO] - 	                    (2, 2.265553102493286),
[2025-02-17 17:50:12,032][flwr][INFO] - 	                    (3, 2.225464366277059),
[2025-02-17 17:50:12,032][flwr][INFO] - 	                    (4, 2.132017782529195),
[2025-02-17 17:50:12,032][flwr][INFO] - 	                    (5, 1.965737685362498),
[2025-02-17 17:50:12,032][flwr][INFO] - 	                    (6, 1.8239379017441362),
[2025-02-17 17:50:12,032][flwr][INFO] - 	                    (7, 1.9056181859970094),
[2025-02-17 17:50:12,032][flwr][INFO] - 	                    (8, 2.3689539670944213),
[2025-02-17 17:50:12,033][flwr][INFO] - 	                    (9, 3.2472753480628684),
[2025-02-17 17:50:12,033][flwr][INFO] - 	                    (10, 4.774023337364197),
[2025-02-17 17:50:12,033][flwr][INFO] - 	                    (11, 7.029546252886454),
[2025-02-17 17:50:12,033][flwr][INFO] - 	                    (12, 10.303258066177369),
[2025-02-17 17:50:12,033][flwr][INFO] - 	                    (13, 14.856507727305095),
[2025-02-17 17:50:12,033][flwr][INFO] - 	                    (14, 20.914114774068196),
[2025-02-17 17:50:12,033][flwr][INFO] - 	                    (15, 28.91126719792684),
[2025-02-17 17:50:12,033][flwr][INFO] - 	                    (16, 39.133213907877604),
[2025-02-17 17:50:12,033][flwr][INFO] - 	                    (17, 51.910803146362305),
[2025-02-17 17:50:12,033][flwr][INFO] - 	                    (18, 67.80024430592854),
[2025-02-17 17:50:12,033][flwr][INFO] - 	                    (19, 87.29675163269043),
[2025-02-17 17:50:12,033][flwr][INFO] - 	                    (20, 110.7403757985433)]}
[2025-02-17 17:50:12,033][flwr][INFO] - 	History (metrics, distributed, evaluate):
[2025-02-17 17:50:12,034][flwr][INFO] - 	{'clients_accuracies': [(1, 0.11916666666666667),
[2025-02-17 17:50:12,034][flwr][INFO] - 	                        (2, 0.14916666666666667),
[2025-02-17 17:50:12,034][flwr][INFO] - 	                        (3, 0.17333333333333334),
[2025-02-17 17:50:12,034][flwr][INFO] - 	                        (4, 0.31166666666666665),
[2025-02-17 17:50:12,034][flwr][INFO] - 	                        (5, 0.385),
[2025-02-17 17:50:12,034][flwr][INFO] - 	                        (6, 0.42416666666666664),
[2025-02-17 17:50:12,034][flwr][INFO] - 	                        (7, 0.4566666666666667),
[2025-02-17 17:50:12,034][flwr][INFO] - 	                        (8, 0.4593750000000001),
[2025-02-17 17:50:12,034][flwr][INFO] - 	                        (9, 0.45500000000000007),
[2025-02-17 17:50:12,034][flwr][INFO] - 	                        (10, 0.43666666666666665),
[2025-02-17 17:50:12,034][flwr][INFO] - 	                        (11, 0.41083333333333333),
[2025-02-17 17:50:12,034][flwr][INFO] - 	                        (12, 0.3916666666666667),
[2025-02-17 17:50:12,034][flwr][INFO] - 	                        (13, 0.3691666666666667),
[2025-02-17 17:50:12,035][flwr][INFO] - 	                        (14, 0.35833333333333334),
[2025-02-17 17:50:12,035][flwr][INFO] - 	                        (15, 0.3516666666666667),
[2025-02-17 17:50:12,035][flwr][INFO] - 	                        (16, 0.3466666666666667),
[2025-02-17 17:50:12,035][flwr][INFO] - 	                        (17, 0.3441666666666666),
[2025-02-17 17:50:12,035][flwr][INFO] - 	                        (18, 0.32916666666666666),
[2025-02-17 17:50:12,035][flwr][INFO] - 	                        (19, 0.31416666666666665),
[2025-02-17 17:50:12,035][flwr][INFO] - 	                        (20, 0.30500000000000005)],
[2025-02-17 17:50:12,035][flwr][INFO] - 	 'clients_losses': [(1, 0.07607730786005655),
[2025-02-17 17:50:12,035][flwr][INFO] - 	                    (2, 0.07533424019813538),
[2025-02-17 17:50:12,035][flwr][INFO] - 	                    (3, 0.07350963393847147),
[2025-02-17 17:50:12,035][flwr][INFO] - 	                    (4, 0.06918202410141627),
[2025-02-17 17:50:12,035][flwr][INFO] - 	                    (5, 0.06399892777204515),
[2025-02-17 17:50:12,035][flwr][INFO] - 	                    (6, 0.06308051556348801),
[2025-02-17 17:50:12,036][flwr][INFO] - 	                    (7, 0.0761088451743126),
[2025-02-17 17:50:12,036][flwr][INFO] - 	                    (8, 0.10416750013828278),
[2025-02-17 17:50:12,036][flwr][INFO] - 	                    (9, 0.14949003239472708),
[2025-02-17 17:50:12,036][flwr][INFO] - 	                    (10, 0.2191708385944367),
[2025-02-17 17:50:12,036][flwr][INFO] - 	                    (11, 0.32210256973902385),
[2025-02-17 17:50:12,036][flwr][INFO] - 	                    (12, 0.46376338203748063),
[2025-02-17 17:50:12,036][flwr][INFO] - 	                    (13, 0.6572337683041891),
[2025-02-17 17:50:12,036][flwr][INFO] - 	                    (14, 0.9145108207066854),
[2025-02-17 17:50:12,036][flwr][INFO] - 	                    (15, 1.2540117454528807),
[2025-02-17 17:50:12,036][flwr][INFO] - 	                    (16, 1.6810016345977783),
[2025-02-17 17:50:12,036][flwr][INFO] - 	                    (17, 2.2102743117014567),
[2025-02-17 17:50:12,036][flwr][INFO] - 	                    (18, 2.866259644826253),
[2025-02-17 17:50:12,036][flwr][INFO] - 	                    (19, 3.6701636028289792),
[2025-02-17 17:50:12,037][flwr][INFO] - 	                    (20, 4.640328458150228)]}
[2025-02-17 17:50:12,037][flwr][INFO] - 	History (metrics, centralized):
[2025-02-17 17:50:12,037][flwr][INFO] - 	{'accuracy': [(0, 0.0958),
[2025-02-17 17:50:12,037][flwr][INFO] - 	              (1, 0.1288),
[2025-02-17 17:50:12,037][flwr][INFO] - 	              (2, 0.1495),
[2025-02-17 17:50:12,037][flwr][INFO] - 	              (3, 0.1659),
[2025-02-17 17:50:12,037][flwr][INFO] - 	              (4, 0.3314),
[2025-02-17 17:50:12,037][flwr][INFO] - 	              (5, 0.4105),
[2025-02-17 17:50:12,037][flwr][INFO] - 	              (6, 0.4459),
[2025-02-17 17:50:12,037][flwr][INFO] - 	              (7, 0.4714),
[2025-02-17 17:50:12,037][flwr][INFO] - 	              (8, 0.4742),
[2025-02-17 17:50:12,037][flwr][INFO] - 	              (9, 0.4693),
[2025-02-17 17:50:12,037][flwr][INFO] - 	              (10, 0.4568),
[2025-02-17 17:50:12,038][flwr][INFO] - 	              (11, 0.4362),
[2025-02-17 17:50:12,038][flwr][INFO] - 	              (12, 0.4155),
[2025-02-17 17:50:12,038][flwr][INFO] - 	              (13, 0.3999),
[2025-02-17 17:50:12,038][flwr][INFO] - 	              (14, 0.3845),
[2025-02-17 17:50:12,038][flwr][INFO] - 	              (15, 0.3703),
[2025-02-17 17:50:12,038][flwr][INFO] - 	              (16, 0.3586),
[2025-02-17 17:50:12,038][flwr][INFO] - 	              (17, 0.3478),
[2025-02-17 17:50:12,038][flwr][INFO] - 	              (18, 0.3386),
[2025-02-17 17:50:12,038][flwr][INFO] - 	              (19, 0.333),
[2025-02-17 17:50:12,038][flwr][INFO] - 	              (20, 0.3298)]}
[2025-02-17 17:50:12,038][flwr][INFO] - 
