[2025-02-10 04:09:58,916][flwr][INFO] - Starting Flower ServerApp, config: num_rounds=20, no round_timeout
[2025-02-10 04:09:58,917][flwr][INFO] - 
[2025-02-10 04:09:58,918][flwr][INFO] - [INIT]
[2025-02-10 04:09:58,918][flwr][INFO] - Using initial global parameters provided by strategy
[2025-02-10 04:09:58,918][flwr][INFO] - Starting evaluation of initial global parameters
[2025-02-10 04:10:07,114][flwr][INFO] - initial parameters (loss, other metrics): 0.07237841854095459, {'accuracy': 0.0628}
[2025-02-10 04:10:07,115][flwr][INFO] - 
[2025-02-10 04:10:07,115][flwr][INFO] - [ROUND 1]
[2025-02-10 04:10:07,115][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 04:10:37,263][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 04:10:43,197][flwr][INFO] - fit progress: (1, 0.07162653896808624, {'accuracy': 0.1688}, 36.08219738500338)
[2025-02-10 04:10:43,197][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 04:11:05,829][flwr][INFO] - aggregate_evaluate: received 20 results and 0 failures
[2025-02-10 04:11:05,830][flwr][INFO] - 
[2025-02-10 04:11:05,830][flwr][INFO] - [ROUND 2]
[2025-02-10 04:11:05,830][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 04:11:30,810][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 04:11:36,271][flwr][INFO] - fit progress: (2, 0.07083907408714295, {'accuracy': 0.2507}, 89.15636341900245)
[2025-02-10 04:11:36,271][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 04:12:00,307][flwr][INFO] - aggregate_evaluate: received 20 results and 0 failures
[2025-02-10 04:12:00,307][flwr][INFO] - 
[2025-02-10 04:12:00,307][flwr][INFO] - [ROUND 3]
[2025-02-10 04:12:00,307][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 04:12:26,081][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 04:12:31,571][flwr][INFO] - fit progress: (3, 0.06961600227355957, {'accuracy': 0.3952}, 144.45628115200088)
[2025-02-10 04:12:31,571][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 04:12:54,405][flwr][INFO] - aggregate_evaluate: received 20 results and 0 failures
[2025-02-10 04:12:54,406][flwr][INFO] - 
[2025-02-10 04:12:54,406][flwr][INFO] - [ROUND 4]
[2025-02-10 04:12:54,406][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 04:13:20,345][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 04:13:25,653][flwr][INFO] - fit progress: (4, 0.06763157362937927, {'accuracy': 0.4905}, 198.53830434499832)
[2025-02-10 04:13:25,653][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 04:13:48,923][flwr][INFO] - aggregate_evaluate: received 20 results and 0 failures
[2025-02-10 04:13:48,923][flwr][INFO] - 
[2025-02-10 04:13:48,923][flwr][INFO] - [ROUND 5]
[2025-02-10 04:13:48,923][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 04:14:13,406][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 04:14:19,034][flwr][INFO] - fit progress: (5, 0.06449291954040527, {'accuracy': 0.5341}, 251.91935011599708)
[2025-02-10 04:14:19,034][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 04:14:41,488][flwr][INFO] - aggregate_evaluate: received 20 results and 0 failures
[2025-02-10 04:14:41,488][flwr][INFO] - 
[2025-02-10 04:14:41,488][flwr][INFO] - [ROUND 6]
[2025-02-10 04:14:41,489][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 04:15:06,376][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 04:15:11,217][flwr][INFO] - fit progress: (6, 0.06022932224273682, {'accuracy': 0.5516}, 304.1026727749995)
[2025-02-10 04:15:11,217][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 04:15:36,959][flwr][INFO] - aggregate_evaluate: received 20 results and 0 failures
[2025-02-10 04:15:36,960][flwr][INFO] - 
[2025-02-10 04:15:36,960][flwr][INFO] - [ROUND 7]
[2025-02-10 04:15:36,960][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 04:16:03,731][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 04:16:09,598][flwr][INFO] - fit progress: (7, 0.054877919507026675, {'accuracy': 0.5995}, 362.4830764520011)
[2025-02-10 04:16:09,598][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 04:16:32,930][flwr][INFO] - aggregate_evaluate: received 20 results and 0 failures
[2025-02-10 04:16:32,930][flwr][INFO] - 
[2025-02-10 04:16:32,931][flwr][INFO] - [ROUND 8]
[2025-02-10 04:16:32,931][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 04:17:00,118][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 04:17:05,710][flwr][INFO] - fit progress: (8, 0.04917772091627121, {'accuracy': 0.6132}, 418.59576308599935)
[2025-02-10 04:17:05,711][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 04:17:29,647][flwr][INFO] - aggregate_evaluate: received 20 results and 0 failures
[2025-02-10 04:17:29,647][flwr][INFO] - 
[2025-02-10 04:17:29,647][flwr][INFO] - [ROUND 9]
[2025-02-10 04:17:29,647][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 04:17:55,987][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 04:18:01,383][flwr][INFO] - fit progress: (9, 0.043894259214401245, {'accuracy': 0.647}, 474.2689231980039)
[2025-02-10 04:18:01,384][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 04:18:25,220][flwr][INFO] - aggregate_evaluate: received 20 results and 0 failures
[2025-02-10 04:18:25,220][flwr][INFO] - 
[2025-02-10 04:18:25,220][flwr][INFO] - [ROUND 10]
[2025-02-10 04:18:25,221][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 04:18:52,261][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 04:18:57,337][flwr][INFO] - fit progress: (10, 0.039849380803108216, {'accuracy': 0.6477}, 530.2228528220003)
[2025-02-10 04:18:57,338][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 04:19:20,172][flwr][INFO] - aggregate_evaluate: received 20 results and 0 failures
[2025-02-10 04:19:20,172][flwr][INFO] - 
[2025-02-10 04:19:20,172][flwr][INFO] - [ROUND 11]
[2025-02-10 04:19:20,173][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 04:19:45,110][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 04:19:50,323][flwr][INFO] - fit progress: (11, 0.03613715544939041, {'accuracy': 0.6698}, 583.2080634710001)
[2025-02-10 04:19:50,323][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 04:20:23,316][flwr][ERROR] - An exception was raised when processing a message by RayBackend
[2025-02-10 04:20:23,316][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=4743, ip=172.27.85.201, actor_id=d00ad53cf28daa5e7210b39e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f2af00a3210>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4743, ip=172.27.85.201, actor_id=d00ad53cf28daa5e7210b39e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f2af00a3210>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 105, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4743, ip=172.27.85.201, actor_id=d00ad53cf28daa5e7210b39e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f2af00a3210>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c
[2025-02-10 04:20:23,318][flwr][ERROR] - Traceback (most recent call last):
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py", line 112, in worker
    out_mssg, updated_context = backend.process_message(message, context)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 187, in process_message
    raise ex
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 175, in process_message
    ) = self.pool.fetch_result_and_return_actor_to_pool(future)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 478, in fetch_result_and_return_actor_to_pool
    _, out_mssg, updated_context = ray.get(future)
                                   ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=4743, ip=172.27.85.201, actor_id=d00ad53cf28daa5e7210b39e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f2af00a3210>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4743, ip=172.27.85.201, actor_id=d00ad53cf28daa5e7210b39e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f2af00a3210>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 105, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4743, ip=172.27.85.201, actor_id=d00ad53cf28daa5e7210b39e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f2af00a3210>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

[2025-02-10 04:20:25,461][flwr][ERROR] - An exception was raised when processing a message by RayBackend
[2025-02-10 04:20:25,461][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=4744, ip=172.27.85.201, actor_id=586df575719f58d4aae8e41801000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f26c436af90>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4744, ip=172.27.85.201, actor_id=586df575719f58d4aae8e41801000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f26c436af90>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 105, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4744, ip=172.27.85.201, actor_id=586df575719f58d4aae8e41801000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f26c436af90>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c
[2025-02-10 04:20:25,462][flwr][ERROR] - Traceback (most recent call last):
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py", line 112, in worker
    out_mssg, updated_context = backend.process_message(message, context)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 187, in process_message
    raise ex
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 175, in process_message
    ) = self.pool.fetch_result_and_return_actor_to_pool(future)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 478, in fetch_result_and_return_actor_to_pool
    _, out_mssg, updated_context = ray.get(future)
                                   ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=4744, ip=172.27.85.201, actor_id=586df575719f58d4aae8e41801000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f26c436af90>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4744, ip=172.27.85.201, actor_id=586df575719f58d4aae8e41801000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f26c436af90>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 105, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4744, ip=172.27.85.201, actor_id=586df575719f58d4aae8e41801000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f26c436af90>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

[2025-02-10 04:22:10,011][flwr][ERROR] - An exception was raised when processing a message by RayBackend
[2025-02-10 04:22:10,011][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=4742, ip=172.27.85.201, actor_id=7dc297d61825792a257cba8201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f7e0427aed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4742, ip=172.27.85.201, actor_id=7dc297d61825792a257cba8201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f7e0427aed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 105, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4742, ip=172.27.85.201, actor_id=7dc297d61825792a257cba8201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f7e0427aed0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c
[2025-02-10 04:22:10,012][flwr][ERROR] - Traceback (most recent call last):
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py", line 112, in worker
    out_mssg, updated_context = backend.process_message(message, context)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 187, in process_message
    raise ex
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 175, in process_message
    ) = self.pool.fetch_result_and_return_actor_to_pool(future)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 478, in fetch_result_and_return_actor_to_pool
    _, out_mssg, updated_context = ray.get(future)
                                   ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=4742, ip=172.27.85.201, actor_id=7dc297d61825792a257cba8201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f7e0427aed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4742, ip=172.27.85.201, actor_id=7dc297d61825792a257cba8201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f7e0427aed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 105, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4742, ip=172.27.85.201, actor_id=7dc297d61825792a257cba8201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f7e0427aed0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

[2025-02-10 04:22:10,112][flwr][INFO] - aggregate_evaluate: received 17 results and 3 failures
[2025-02-10 04:22:10,112][flwr][INFO] - 
[2025-02-10 04:22:10,112][flwr][INFO] - [ROUND 12]
[2025-02-10 04:22:10,112][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 04:22:36,181][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 04:22:41,124][flwr][INFO] - fit progress: (12, 0.033124090534448626, {'accuracy': 0.6965}, 754.009429974998)
[2025-02-10 04:22:41,124][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 04:23:03,876][flwr][INFO] - aggregate_evaluate: received 20 results and 0 failures
[2025-02-10 04:23:03,877][flwr][INFO] - 
[2025-02-10 04:23:03,877][flwr][INFO] - [ROUND 13]
[2025-02-10 04:23:03,877][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 04:23:28,761][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 04:23:34,521][flwr][INFO] - fit progress: (13, 0.03025607500076294, {'accuracy': 0.7197}, 807.4067572799977)
[2025-02-10 04:23:34,521][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 04:23:58,356][flwr][INFO] - aggregate_evaluate: received 20 results and 0 failures
[2025-02-10 04:23:58,357][flwr][INFO] - 
[2025-02-10 04:23:58,357][flwr][INFO] - [ROUND 14]
[2025-02-10 04:23:58,357][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 04:24:24,227][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 04:24:29,136][flwr][INFO] - fit progress: (14, 0.02856091980934143, {'accuracy': 0.717}, 862.021031723998)
[2025-02-10 04:24:29,136][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 04:24:52,009][flwr][INFO] - aggregate_evaluate: received 20 results and 0 failures
[2025-02-10 04:24:52,010][flwr][INFO] - 
[2025-02-10 04:24:52,010][flwr][INFO] - [ROUND 15]
[2025-02-10 04:24:52,010][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 04:25:17,866][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 04:25:23,155][flwr][INFO] - fit progress: (15, 0.026640375927090645, {'accuracy': 0.735}, 916.0400857770001)
[2025-02-10 04:25:23,155][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 04:25:47,088][flwr][INFO] - aggregate_evaluate: received 20 results and 0 failures
[2025-02-10 04:25:47,089][flwr][INFO] - 
[2025-02-10 04:25:47,089][flwr][INFO] - [ROUND 16]
[2025-02-10 04:25:47,089][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 04:26:11,754][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 04:26:17,547][flwr][INFO] - fit progress: (16, 0.024912629553675653, {'accuracy': 0.7535}, 970.4326243219984)
[2025-02-10 04:26:17,547][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 04:26:39,481][flwr][INFO] - aggregate_evaluate: received 20 results and 0 failures
[2025-02-10 04:26:39,481][flwr][INFO] - 
[2025-02-10 04:26:39,481][flwr][INFO] - [ROUND 17]
[2025-02-10 04:26:39,481][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 04:27:04,119][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 04:27:09,494][flwr][INFO] - fit progress: (17, 0.024300764209032058, {'accuracy': 0.7474}, 1022.379915012003)
[2025-02-10 04:27:09,495][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 04:27:32,428][flwr][INFO] - aggregate_evaluate: received 20 results and 0 failures
[2025-02-10 04:27:32,428][flwr][INFO] - 
[2025-02-10 04:27:32,428][flwr][INFO] - [ROUND 18]
[2025-02-10 04:27:32,429][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 04:27:57,868][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 04:28:03,116][flwr][INFO] - fit progress: (18, 0.022969726970791818, {'accuracy': 0.7615}, 1076.001356061999)
[2025-02-10 04:28:03,116][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 04:28:26,849][flwr][INFO] - aggregate_evaluate: received 20 results and 0 failures
[2025-02-10 04:28:26,850][flwr][INFO] - 
[2025-02-10 04:28:26,850][flwr][INFO] - [ROUND 19]
[2025-02-10 04:28:26,850][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 04:28:54,735][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 04:29:00,504][flwr][INFO] - fit progress: (19, 0.022526973795890807, {'accuracy': 0.7656}, 1133.3895284329992)
[2025-02-10 04:29:00,504][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 04:29:25,941][flwr][INFO] - aggregate_evaluate: received 20 results and 0 failures
[2025-02-10 04:29:25,941][flwr][INFO] - 
[2025-02-10 04:29:25,941][flwr][INFO] - [ROUND 20]
[2025-02-10 04:29:25,941][flwr][INFO] - configure_fit: strategy sampled 20 clients (out of 20)
[2025-02-10 04:29:52,407][flwr][INFO] - aggregate_fit: received 20 results and 0 failures
[2025-02-10 04:29:58,433][flwr][INFO] - fit progress: (20, 0.022027679213881494, {'accuracy': 0.7694}, 1191.3189584249994)
[2025-02-10 04:29:58,434][flwr][INFO] - configure_evaluate: strategy sampled 20 clients (out of 20)
[2025-02-10 04:30:26,003][flwr][INFO] - aggregate_evaluate: received 20 results and 0 failures
[2025-02-10 04:30:26,003][flwr][INFO] - 
[2025-02-10 04:30:26,003][flwr][INFO] - [SUMMARY]
[2025-02-10 04:30:26,003][flwr][INFO] - Run finished 20 round(s) in 1218.89s
[2025-02-10 04:30:26,004][flwr][INFO] - 	History (loss, distributed):
[2025-02-10 04:30:26,004][flwr][INFO] - 		round 1: 0.07627205044031142
[2025-02-10 04:30:26,004][flwr][INFO] - 		round 2: 0.0754628837108612
[2025-02-10 04:30:26,004][flwr][INFO] - 		round 3: 0.07419131447871527
[2025-02-10 04:30:26,004][flwr][INFO] - 		round 4: 0.07212198426326116
[2025-02-10 04:30:26,004][flwr][INFO] - 		round 5: 0.06881694351633388
[2025-02-10 04:30:26,005][flwr][INFO] - 		round 6: 0.06432943478226662
[2025-02-10 04:30:26,005][flwr][INFO] - 		round 7: 0.05867252280314763
[2025-02-10 04:30:26,005][flwr][INFO] - 		round 8: 0.05270287156105041
[2025-02-10 04:30:26,005][flwr][INFO] - 		round 9: 0.047092005411783856
[2025-02-10 04:30:26,005][flwr][INFO] - 		round 10: 0.04292389857272307
[2025-02-10 04:30:26,005][flwr][INFO] - 		round 11: 0.03880822106319315
[2025-02-10 04:30:26,005][flwr][INFO] - 		round 12: 0.03586746096611022
[2025-02-10 04:30:26,005][flwr][INFO] - 		round 13: 0.03304428140322367
[2025-02-10 04:30:26,005][flwr][INFO] - 		round 14: 0.031173128659526504
[2025-02-10 04:30:26,005][flwr][INFO] - 		round 15: 0.029097202134629085
[2025-02-10 04:30:26,005][flwr][INFO] - 		round 16: 0.027220149015386903
[2025-02-10 04:30:26,005][flwr][INFO] - 		round 17: 0.02649626406530539
[2025-02-10 04:30:26,005][flwr][INFO] - 		round 18: 0.025020719518264133
[2025-02-10 04:30:26,006][flwr][INFO] - 		round 19: 0.024609979800879957
[2025-02-10 04:30:26,006][flwr][INFO] - 		round 20: 0.023879238851368428
[2025-02-10 04:30:26,006][flwr][INFO] - 	History (loss, centralized):
[2025-02-10 04:30:26,006][flwr][INFO] - 		round 0: 0.07237841854095459
[2025-02-10 04:30:26,006][flwr][INFO] - 		round 1: 0.07162653896808624
[2025-02-10 04:30:26,006][flwr][INFO] - 		round 2: 0.07083907408714295
[2025-02-10 04:30:26,006][flwr][INFO] - 		round 3: 0.06961600227355957
[2025-02-10 04:30:26,006][flwr][INFO] - 		round 4: 0.06763157362937927
[2025-02-10 04:30:26,006][flwr][INFO] - 		round 5: 0.06449291954040527
[2025-02-10 04:30:26,006][flwr][INFO] - 		round 6: 0.06022932224273682
[2025-02-10 04:30:26,006][flwr][INFO] - 		round 7: 0.054877919507026675
[2025-02-10 04:30:26,006][flwr][INFO] - 		round 8: 0.04917772091627121
[2025-02-10 04:30:26,006][flwr][INFO] - 		round 9: 0.043894259214401245
[2025-02-10 04:30:26,007][flwr][INFO] - 		round 10: 0.039849380803108216
[2025-02-10 04:30:26,007][flwr][INFO] - 		round 11: 0.03613715544939041
[2025-02-10 04:30:26,007][flwr][INFO] - 		round 12: 0.033124090534448626
[2025-02-10 04:30:26,007][flwr][INFO] - 		round 13: 0.03025607500076294
[2025-02-10 04:30:26,007][flwr][INFO] - 		round 14: 0.02856091980934143
[2025-02-10 04:30:26,007][flwr][INFO] - 		round 15: 0.026640375927090645
[2025-02-10 04:30:26,007][flwr][INFO] - 		round 16: 0.024912629553675653
[2025-02-10 04:30:26,007][flwr][INFO] - 		round 17: 0.024300764209032058
[2025-02-10 04:30:26,007][flwr][INFO] - 		round 18: 0.022969726970791818
[2025-02-10 04:30:26,007][flwr][INFO] - 		round 19: 0.022526973795890807
[2025-02-10 04:30:26,007][flwr][INFO] - 		round 20: 0.022027679213881494
[2025-02-10 04:30:26,007][flwr][INFO] - 	History (metrics, distributed, fit):
[2025-02-10 04:30:26,007][flwr][INFO] - 	{'clients_epsilons': [(1, 0.6813471387867438),
[2025-02-10 04:30:26,008][flwr][INFO] - 	                      (2, 0.6813471387867438),
[2025-02-10 04:30:26,008][flwr][INFO] - 	                      (3, 0.6813471387867438),
[2025-02-10 04:30:26,008][flwr][INFO] - 	                      (4, 0.6813471387867438),
[2025-02-10 04:30:26,008][flwr][INFO] - 	                      (5, 0.6813471387867438),
[2025-02-10 04:30:26,008][flwr][INFO] - 	                      (6, 0.6813471387867438),
[2025-02-10 04:30:26,008][flwr][INFO] - 	                      (7, 0.6813471387867438),
[2025-02-10 04:30:26,008][flwr][INFO] - 	                      (8, 0.6813471387867438),
[2025-02-10 04:30:26,008][flwr][INFO] - 	                      (9, 0.6813471387867438),
[2025-02-10 04:30:26,008][flwr][INFO] - 	                      (10, 0.6813471387867438),
[2025-02-10 04:30:26,008][flwr][INFO] - 	                      (11, 0.6813471387867438),
[2025-02-10 04:30:26,008][flwr][INFO] - 	                      (12, 0.6813471387867438),
[2025-02-10 04:30:26,008][flwr][INFO] - 	                      (13, 0.6813471387867438),
[2025-02-10 04:30:26,009][flwr][INFO] - 	                      (14, 0.6813471387867438),
[2025-02-10 04:30:26,009][flwr][INFO] - 	                      (15, 0.6813471387867438),
[2025-02-10 04:30:26,009][flwr][INFO] - 	                      (16, 0.6813471387867438),
[2025-02-10 04:30:26,009][flwr][INFO] - 	                      (17, 0.6813471387867438),
[2025-02-10 04:30:26,009][flwr][INFO] - 	                      (18, 0.6813471387867438),
[2025-02-10 04:30:26,009][flwr][INFO] - 	                      (19, 0.6813471387867438),
[2025-02-10 04:30:26,009][flwr][INFO] - 	                      (20, 0.6813471387867438)],
[2025-02-10 04:30:26,009][flwr][INFO] - 	 'clients_losses': [(1, 2.3049725341796874),
[2025-02-10 04:30:26,009][flwr][INFO] - 	                    (2, 2.2815278045336407),
[2025-02-10 04:30:26,009][flwr][INFO] - 	                    (3, 2.253563570976257),
[2025-02-10 04:30:26,009][flwr][INFO] - 	                    (4, 2.2108363739649453),
[2025-02-10 04:30:26,009][flwr][INFO] - 	                    (5, 2.13890517950058),
[2025-02-10 04:30:26,009][flwr][INFO] - 	                    (6, 2.0301845892270407),
[2025-02-10 04:30:26,009][flwr][INFO] - 	                    (7, 1.8879960612456004),
[2025-02-10 04:30:26,010][flwr][INFO] - 	                    (8, 1.7203343919912975),
[2025-02-10 04:30:26,010][flwr][INFO] - 	                    (9, 1.546957816282908),
[2025-02-10 04:30:26,010][flwr][INFO] - 	                    (10, 1.3983551545937856),
[2025-02-10 04:30:26,010][flwr][INFO] - 	                    (11, 1.2809157955646515),
[2025-02-10 04:30:26,010][flwr][INFO] - 	                    (12, 1.178709112405777),
[2025-02-10 04:30:26,010][flwr][INFO] - 	                    (13, 1.0842181771993638),
[2025-02-10 04:30:26,010][flwr][INFO] - 	                    (14, 1.0110823621352514),
[2025-02-10 04:30:26,010][flwr][INFO] - 	                    (15, 0.9555107152462006),
[2025-02-10 04:30:26,010][flwr][INFO] - 	                    (16, 0.911507292787234),
[2025-02-10 04:30:26,010][flwr][INFO] - 	                    (17, 0.8599939409891765),
[2025-02-10 04:30:26,010][flwr][INFO] - 	                    (18, 0.8242038185397784),
[2025-02-10 04:30:26,010][flwr][INFO] - 	                    (19, 0.7934262018402417),
[2025-02-10 04:30:26,010][flwr][INFO] - 	                    (20, 0.7744098632534345)]}
[2025-02-10 04:30:26,011][flwr][INFO] - 	History (metrics, distributed, evaluate):
[2025-02-10 04:30:26,011][flwr][INFO] - 	{'clients_accuracies': [(1, 0.18166666666666664),
[2025-02-10 04:30:26,011][flwr][INFO] - 	                        (2, 0.25375000000000003),
[2025-02-10 04:30:26,011][flwr][INFO] - 	                        (3, 0.38958333333333334),
[2025-02-10 04:30:26,011][flwr][INFO] - 	                        (4, 0.47874999999999995),
[2025-02-10 04:30:26,011][flwr][INFO] - 	                        (5, 0.5208333333333334),
[2025-02-10 04:30:26,011][flwr][INFO] - 	                        (6, 0.5508333333333332),
[2025-02-10 04:30:26,011][flwr][INFO] - 	                        (7, 0.5945833333333334),
[2025-02-10 04:30:26,011][flwr][INFO] - 	                        (8, 0.6108333333333331),
[2025-02-10 04:30:26,011][flwr][INFO] - 	                        (9, 0.6387500000000002),
[2025-02-10 04:30:26,011][flwr][INFO] - 	                        (10, 0.6375),
[2025-02-10 04:30:26,011][flwr][INFO] - 	                        (11, 0.6549019607843137),
[2025-02-10 04:30:26,011][flwr][INFO] - 	                        (12, 0.6870833333333333),
[2025-02-10 04:30:26,011][flwr][INFO] - 	                        (13, 0.7079166666666669),
[2025-02-10 04:30:26,011][flwr][INFO] - 	                        (14, 0.7125),
[2025-02-10 04:30:26,012][flwr][INFO] - 	                        (15, 0.7295833333333331),
[2025-02-10 04:30:26,012][flwr][INFO] - 	                        (16, 0.7420833333333333),
[2025-02-10 04:30:26,012][flwr][INFO] - 	                        (17, 0.7395833333333333),
[2025-02-10 04:30:26,012][flwr][INFO] - 	                        (18, 0.7504166666666666),
[2025-02-10 04:30:26,012][flwr][INFO] - 	                        (19, 0.7520833333333333),
[2025-02-10 04:30:26,012][flwr][INFO] - 	                        (20, 0.7575000000000001)],
[2025-02-10 04:30:26,012][flwr][INFO] - 	 'clients_losses': [(1, 0.07627205044031142),
[2025-02-10 04:30:26,012][flwr][INFO] - 	                    (2, 0.0754628837108612),
[2025-02-10 04:30:26,012][flwr][INFO] - 	                    (3, 0.07419131447871527),
[2025-02-10 04:30:26,012][flwr][INFO] - 	                    (4, 0.07212198426326116),
[2025-02-10 04:30:26,012][flwr][INFO] - 	                    (5, 0.06881694351633388),
[2025-02-10 04:30:26,012][flwr][INFO] - 	                    (6, 0.06432943478226662),
[2025-02-10 04:30:26,012][flwr][INFO] - 	                    (7, 0.05867252280314763),
[2025-02-10 04:30:26,012][flwr][INFO] - 	                    (8, 0.05270287156105041),
[2025-02-10 04:30:26,012][flwr][INFO] - 	                    (9, 0.047092005411783856),
[2025-02-10 04:30:26,013][flwr][INFO] - 	                    (10, 0.04292389857272307),
[2025-02-10 04:30:26,013][flwr][INFO] - 	                    (11, 0.03880822106319315),
[2025-02-10 04:30:26,013][flwr][INFO] - 	                    (12, 0.03586746096611022),
[2025-02-10 04:30:26,013][flwr][INFO] - 	                    (13, 0.03304428140322367),
[2025-02-10 04:30:26,013][flwr][INFO] - 	                    (14, 0.031173128659526504),
[2025-02-10 04:30:26,013][flwr][INFO] - 	                    (15, 0.029097202134629085),
[2025-02-10 04:30:26,013][flwr][INFO] - 	                    (16, 0.027220149015386903),
[2025-02-10 04:30:26,013][flwr][INFO] - 	                    (17, 0.02649626406530539),
[2025-02-10 04:30:26,013][flwr][INFO] - 	                    (18, 0.025020719518264133),
[2025-02-10 04:30:26,013][flwr][INFO] - 	                    (19, 0.024609979800879957),
[2025-02-10 04:30:26,013][flwr][INFO] - 	                    (20, 0.023879238851368428)]}
[2025-02-10 04:30:26,013][flwr][INFO] - 	History (metrics, centralized):
[2025-02-10 04:30:26,014][flwr][INFO] - 	{'accuracy': [(0, 0.0628),
[2025-02-10 04:30:26,014][flwr][INFO] - 	              (1, 0.1688),
[2025-02-10 04:30:26,014][flwr][INFO] - 	              (2, 0.2507),
[2025-02-10 04:30:26,014][flwr][INFO] - 	              (3, 0.3952),
[2025-02-10 04:30:26,014][flwr][INFO] - 	              (4, 0.4905),
[2025-02-10 04:30:26,014][flwr][INFO] - 	              (5, 0.5341),
[2025-02-10 04:30:26,014][flwr][INFO] - 	              (6, 0.5516),
[2025-02-10 04:30:26,014][flwr][INFO] - 	              (7, 0.5995),
[2025-02-10 04:30:26,014][flwr][INFO] - 	              (8, 0.6132),
[2025-02-10 04:30:26,014][flwr][INFO] - 	              (9, 0.647),
[2025-02-10 04:30:26,014][flwr][INFO] - 	              (10, 0.6477),
[2025-02-10 04:30:26,014][flwr][INFO] - 	              (11, 0.6698),
[2025-02-10 04:30:26,014][flwr][INFO] - 	              (12, 0.6965),
[2025-02-10 04:30:26,014][flwr][INFO] - 	              (13, 0.7197),
[2025-02-10 04:30:26,015][flwr][INFO] - 	              (14, 0.717),
[2025-02-10 04:30:26,015][flwr][INFO] - 	              (15, 0.735),
[2025-02-10 04:30:26,015][flwr][INFO] - 	              (16, 0.7535),
[2025-02-10 04:30:26,015][flwr][INFO] - 	              (17, 0.7474),
[2025-02-10 04:30:26,015][flwr][INFO] - 	              (18, 0.7615),
[2025-02-10 04:30:26,015][flwr][INFO] - 	              (19, 0.7656),
[2025-02-10 04:30:26,015][flwr][INFO] - 	              (20, 0.7694)]}
[2025-02-10 04:30:26,015][flwr][INFO] - 
