[2025-02-10 00:32:11,153][flwr][INFO] - Starting Flower ServerApp, config: num_rounds=20, no round_timeout
[2025-02-10 00:32:11,153][flwr][INFO] - 
[2025-02-10 00:32:11,154][flwr][INFO] - [INIT]
[2025-02-10 00:32:11,154][flwr][INFO] - Using initial global parameters provided by strategy
[2025-02-10 00:32:11,154][flwr][INFO] - Starting evaluation of initial global parameters
[2025-02-10 00:32:18,876][flwr][INFO] - initial parameters (loss, other metrics): 0.0721090440750122, {'accuracy': 0.0788}
[2025-02-10 00:32:18,877][flwr][INFO] - 
[2025-02-10 00:32:18,877][flwr][INFO] - [ROUND 1]
[2025-02-10 00:32:18,877][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-10 00:32:38,007][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-10 00:32:43,481][flwr][INFO] - fit progress: (1, 0.07170669438838959, {'accuracy': 0.1085}, 24.604343216997222)
[2025-02-10 00:32:43,481][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-10 00:32:56,403][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-10 00:32:56,403][flwr][INFO] - 
[2025-02-10 00:32:56,403][flwr][INFO] - [ROUND 2]
[2025-02-10 00:32:56,404][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-10 00:33:10,927][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-10 00:33:16,182][flwr][INFO] - fit progress: (2, 0.07130758595466614, {'accuracy': 0.1699}, 57.30580427699897)
[2025-02-10 00:33:16,183][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-10 00:33:28,801][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-10 00:33:28,802][flwr][INFO] - 
[2025-02-10 00:33:28,802][flwr][INFO] - [ROUND 3]
[2025-02-10 00:33:28,802][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-10 00:33:43,123][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-10 00:33:48,678][flwr][INFO] - fit progress: (3, 0.07059015321731567, {'accuracy': 0.3692}, 89.80150516400317)
[2025-02-10 00:33:48,678][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-10 00:34:01,698][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-10 00:34:01,699][flwr][INFO] - 
[2025-02-10 00:34:01,699][flwr][INFO] - [ROUND 4]
[2025-02-10 00:34:01,699][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-10 00:34:15,922][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-10 00:34:21,083][flwr][INFO] - fit progress: (4, 0.06944794516563416, {'accuracy': 0.4022}, 122.20636710200051)
[2025-02-10 00:34:21,083][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-10 00:34:36,205][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-10 00:34:36,205][flwr][INFO] - 
[2025-02-10 00:34:36,205][flwr][INFO] - [ROUND 5]
[2025-02-10 00:34:36,205][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-10 00:34:51,937][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-10 00:34:59,429][flwr][INFO] - fit progress: (5, 0.06747148971557618, {'accuracy': 0.3911}, 160.55196811600035)
[2025-02-10 00:34:59,429][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-10 00:35:13,854][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-10 00:35:13,854][flwr][INFO] - 
[2025-02-10 00:35:13,854][flwr][INFO] - [ROUND 6]
[2025-02-10 00:35:13,854][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-10 00:35:27,777][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-10 00:35:33,231][flwr][INFO] - fit progress: (6, 0.06452898335456848, {'accuracy': 0.4648}, 194.3544991020026)
[2025-02-10 00:35:33,231][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-10 00:35:46,351][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-10 00:35:46,351][flwr][INFO] - 
[2025-02-10 00:35:46,351][flwr][INFO] - [ROUND 7]
[2025-02-10 00:35:46,351][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-10 00:36:00,874][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-10 00:36:06,300][flwr][INFO] - fit progress: (7, 0.06058321347236633, {'accuracy': 0.5363}, 227.4230359830035)
[2025-02-10 00:36:06,300][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-10 00:36:20,120][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-10 00:36:20,121][flwr][INFO] - 
[2025-02-10 00:36:20,121][flwr][INFO] - [ROUND 8]
[2025-02-10 00:36:20,121][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-10 00:36:34,243][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-10 00:36:39,809][flwr][INFO] - fit progress: (8, 0.05507335557937622, {'accuracy': 0.5929}, 260.9321004329977)
[2025-02-10 00:36:39,809][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-10 00:36:52,430][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-10 00:36:52,431][flwr][INFO] - 
[2025-02-10 00:36:52,431][flwr][INFO] - [ROUND 9]
[2025-02-10 00:36:52,431][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-10 00:37:11,761][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-10 00:37:16,726][flwr][INFO] - fit progress: (9, 0.04925865445137024, {'accuracy': 0.6296}, 297.8498521579968)
[2025-02-10 00:37:16,727][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-10 00:37:29,547][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-10 00:37:29,548][flwr][INFO] - 
[2025-02-10 00:37:29,548][flwr][INFO] - [ROUND 10]
[2025-02-10 00:37:29,548][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-10 00:37:43,670][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-10 00:37:48,607][flwr][INFO] - fit progress: (10, 0.043669030344486236, {'accuracy': 0.6694}, 329.72997020299954)
[2025-02-10 00:37:48,607][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-10 00:38:01,527][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-10 00:38:01,528][flwr][INFO] - 
[2025-02-10 00:38:01,528][flwr][INFO] - [ROUND 11]
[2025-02-10 00:38:01,528][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-10 00:38:16,152][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-10 00:38:21,066][flwr][INFO] - fit progress: (11, 0.03877113295197487, {'accuracy': 0.6735}, 362.1890175009976)
[2025-02-10 00:38:21,066][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-10 00:38:34,186][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-10 00:38:34,187][flwr][INFO] - 
[2025-02-10 00:38:34,187][flwr][INFO] - [ROUND 12]
[2025-02-10 00:38:34,187][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-10 00:38:48,310][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-10 00:38:53,707][flwr][INFO] - fit progress: (12, 0.034339886343479155, {'accuracy': 0.7032}, 394.8299077219999)
[2025-02-10 00:38:53,707][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-10 00:39:07,429][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-10 00:39:07,429][flwr][INFO] - 
[2025-02-10 00:39:07,429][flwr][INFO] - [ROUND 13]
[2025-02-10 00:39:07,429][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-10 00:39:21,251][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-10 00:39:26,293][flwr][INFO] - fit progress: (13, 0.0313410772383213, {'accuracy': 0.7067}, 427.4160096880005)
[2025-02-10 00:39:26,293][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-10 00:39:39,113][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-10 00:39:39,113][flwr][INFO] - 
[2025-02-10 00:39:39,114][flwr][INFO] - [ROUND 14]
[2025-02-10 00:39:39,114][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-10 00:39:53,238][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-10 00:39:58,368][flwr][INFO] - fit progress: (14, 0.028417218846082688, {'accuracy': 0.7151}, 459.49087573900033)
[2025-02-10 00:39:58,368][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-10 00:40:11,389][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-10 00:40:11,390][flwr][INFO] - 
[2025-02-10 00:40:11,390][flwr][INFO] - [ROUND 15]
[2025-02-10 00:40:11,390][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-10 00:40:25,814][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-10 00:40:31,109][flwr][INFO] - fit progress: (15, 0.02645457138121128, {'accuracy': 0.739}, 492.23220807100006)
[2025-02-10 00:40:31,109][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-10 00:40:44,030][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-10 00:40:44,030][flwr][INFO] - 
[2025-02-10 00:40:44,030][flwr][INFO] - [ROUND 16]
[2025-02-10 00:40:44,030][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-10 00:40:58,755][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-10 00:41:03,707][flwr][INFO] - fit progress: (16, 0.024103290197253227, {'accuracy': 0.7515}, 524.8301615050004)
[2025-02-10 00:41:03,707][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-10 00:41:17,727][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-10 00:41:17,727][flwr][INFO] - 
[2025-02-10 00:41:17,727][flwr][INFO] - [ROUND 17]
[2025-02-10 00:41:17,727][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-10 00:41:32,055][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-10 00:41:39,985][flwr][INFO] - fit progress: (17, 0.023280841091275217, {'accuracy': 0.7584}, 561.1079746670002)
[2025-02-10 00:41:39,985][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-10 00:41:54,406][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-10 00:41:54,407][flwr][INFO] - 
[2025-02-10 00:41:54,407][flwr][INFO] - [ROUND 18]
[2025-02-10 00:41:54,407][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-10 00:42:08,628][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-10 00:42:13,508][flwr][INFO] - fit progress: (18, 0.022583679005503655, {'accuracy': 0.7532}, 594.6311827250029)
[2025-02-10 00:42:13,508][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-10 00:42:26,528][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-10 00:42:26,529][flwr][INFO] - 
[2025-02-10 00:42:26,529][flwr][INFO] - [ROUND 19]
[2025-02-10 00:42:26,529][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-10 00:42:40,953][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2025-02-10 00:42:45,820][flwr][INFO] - fit progress: (19, 0.02162578456699848, {'accuracy': 0.7606}, 626.9437672190033)
[2025-02-10 00:42:45,821][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-10 00:43:00,944][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-10 00:43:00,944][flwr][INFO] - 
[2025-02-10 00:43:00,944][flwr][INFO] - [ROUND 20]
[2025-02-10 00:43:00,945][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 10)
[2025-02-10 00:43:17,146][flwr][ERROR] - An exception was raised when processing a message by RayBackend
[2025-02-10 00:43:17,146][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=31368, ip=172.27.85.201, actor_id=cfcf01ba7b6a75a2776426fa01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f7ccc49f510>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=31368, ip=172.27.85.201, actor_id=cfcf01ba7b6a75a2776426fa01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f7ccc49f510>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 105, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=31368, ip=172.27.85.201, actor_id=cfcf01ba7b6a75a2776426fa01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f7ccc49f510>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c
[2025-02-10 00:43:17,148][flwr][ERROR] - Traceback (most recent call last):
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py", line 112, in worker
    out_mssg, updated_context = backend.process_message(message, context)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 187, in process_message
    raise ex
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 175, in process_message
    ) = self.pool.fetch_result_and_return_actor_to_pool(future)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 478, in fetch_result_and_return_actor_to_pool
    _, out_mssg, updated_context = ray.get(future)
                                   ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=31368, ip=172.27.85.201, actor_id=cfcf01ba7b6a75a2776426fa01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f7ccc49f510>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=31368, ip=172.27.85.201, actor_id=cfcf01ba7b6a75a2776426fa01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f7ccc49f510>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 105, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=31368, ip=172.27.85.201, actor_id=cfcf01ba7b6a75a2776426fa01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f7ccc49f510>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

[2025-02-10 00:43:30,202][flwr][ERROR] - An exception was raised when processing a message by RayBackend
[2025-02-10 00:43:30,202][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=31368, ip=172.27.85.201, actor_id=cfcf01ba7b6a75a2776426fa01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f7ccc49f510>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=31368, ip=172.27.85.201, actor_id=cfcf01ba7b6a75a2776426fa01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f7ccc49f510>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 105, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=31368, ip=172.27.85.201, actor_id=cfcf01ba7b6a75a2776426fa01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f7ccc49f510>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c
[2025-02-10 00:43:30,202][flwr][ERROR] - Traceback (most recent call last):
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py", line 112, in worker
    out_mssg, updated_context = backend.process_message(message, context)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 187, in process_message
    raise ex
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 175, in process_message
    ) = self.pool.fetch_result_and_return_actor_to_pool(future)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 478, in fetch_result_and_return_actor_to_pool
    _, out_mssg, updated_context = ray.get(future)
                                   ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=31368, ip=172.27.85.201, actor_id=cfcf01ba7b6a75a2776426fa01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f7ccc49f510>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=31368, ip=172.27.85.201, actor_id=cfcf01ba7b6a75a2776426fa01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f7ccc49f510>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 105, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=31368, ip=172.27.85.201, actor_id=cfcf01ba7b6a75a2776426fa01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f7ccc49f510>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

[2025-02-10 00:43:37,293][flwr][ERROR] - An exception was raised when processing a message by RayBackend
[2025-02-10 00:43:37,293][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=31369, ip=172.27.85.201, actor_id=d94c6b0dc8a05549850567f301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fafdbd681d0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=31369, ip=172.27.85.201, actor_id=d94c6b0dc8a05549850567f301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fafdbd681d0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 105, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=31369, ip=172.27.85.201, actor_id=d94c6b0dc8a05549850567f301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fafdbd681d0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c
[2025-02-10 00:43:37,294][flwr][ERROR] - Traceback (most recent call last):
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py", line 112, in worker
    out_mssg, updated_context = backend.process_message(message, context)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 187, in process_message
    raise ex
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 175, in process_message
    ) = self.pool.fetch_result_and_return_actor_to_pool(future)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 478, in fetch_result_and_return_actor_to_pool
    _, out_mssg, updated_context = ray.get(future)
                                   ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=31369, ip=172.27.85.201, actor_id=d94c6b0dc8a05549850567f301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fafdbd681d0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=31369, ip=172.27.85.201, actor_id=d94c6b0dc8a05549850567f301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fafdbd681d0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 105, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=31369, ip=172.27.85.201, actor_id=d94c6b0dc8a05549850567f301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fafdbd681d0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

[2025-02-10 00:43:44,000][flwr][INFO] - aggregate_fit: received 7 results and 3 failures
[2025-02-10 00:43:49,301][flwr][INFO] - fit progress: (20, 0.02055426798313856, {'accuracy': 0.7811}, 690.423984674002)
[2025-02-10 00:43:49,301][flwr][INFO] - configure_evaluate: strategy sampled 10 clients (out of 10)
[2025-02-10 00:44:02,419][flwr][INFO] - aggregate_evaluate: received 10 results and 0 failures
[2025-02-10 00:44:02,419][flwr][INFO] - 
[2025-02-10 00:44:02,419][flwr][INFO] - [SUMMARY]
[2025-02-10 00:44:02,420][flwr][INFO] - Run finished 20 round(s) in 703.54s
[2025-02-10 00:44:02,420][flwr][INFO] - 	History (loss, distributed):
[2025-02-10 00:44:02,420][flwr][INFO] - 		round 1: 0.07634576618671418
[2025-02-10 00:44:02,421][flwr][INFO] - 		round 2: 0.0759085504213969
[2025-02-10 00:44:02,421][flwr][INFO] - 		round 3: 0.07513303597768148
[2025-02-10 00:44:02,421][flwr][INFO] - 		round 4: 0.07391207794348399
[2025-02-10 00:44:02,421][flwr][INFO] - 		round 5: 0.0718961755434672
[2025-02-10 00:44:02,421][flwr][INFO] - 		round 6: 0.06879389464855193
[2025-02-10 00:44:02,421][flwr][INFO] - 		round 7: 0.06474245131015777
[2025-02-10 00:44:02,421][flwr][INFO] - 		round 8: 0.05896940290927888
[2025-02-10 00:44:02,421][flwr][INFO] - 		round 9: 0.052971772253513336
[2025-02-10 00:44:02,421][flwr][INFO] - 		round 10: 0.04723000874121984
[2025-02-10 00:44:02,421][flwr][INFO] - 		round 11: 0.04205681383609772
[2025-02-10 00:44:02,421][flwr][INFO] - 		round 12: 0.0373799038430055
[2025-02-10 00:44:02,421][flwr][INFO] - 		round 13: 0.03427125652631123
[2025-02-10 00:44:02,421][flwr][INFO] - 		round 14: 0.031176231751839322
[2025-02-10 00:44:02,422][flwr][INFO] - 		round 15: 0.029129256208737686
[2025-02-10 00:44:02,422][flwr][INFO] - 		round 16: 0.026265373031298323
[2025-02-10 00:44:02,422][flwr][INFO] - 		round 17: 0.025336717938383418
[2025-02-10 00:44:02,422][flwr][INFO] - 		round 18: 0.02444769303003947
[2025-02-10 00:44:02,422][flwr][INFO] - 		round 19: 0.023469489316145578
[2025-02-10 00:44:02,422][flwr][INFO] - 		round 20: 0.02214598298072815
[2025-02-10 00:44:02,422][flwr][INFO] - 	History (loss, centralized):
[2025-02-10 00:44:02,422][flwr][INFO] - 		round 0: 0.0721090440750122
[2025-02-10 00:44:02,422][flwr][INFO] - 		round 1: 0.07170669438838959
[2025-02-10 00:44:02,422][flwr][INFO] - 		round 2: 0.07130758595466614
[2025-02-10 00:44:02,422][flwr][INFO] - 		round 3: 0.07059015321731567
[2025-02-10 00:44:02,422][flwr][INFO] - 		round 4: 0.06944794516563416
[2025-02-10 00:44:02,422][flwr][INFO] - 		round 5: 0.06747148971557618
[2025-02-10 00:44:02,423][flwr][INFO] - 		round 6: 0.06452898335456848
[2025-02-10 00:44:02,423][flwr][INFO] - 		round 7: 0.06058321347236633
[2025-02-10 00:44:02,423][flwr][INFO] - 		round 8: 0.05507335557937622
[2025-02-10 00:44:02,423][flwr][INFO] - 		round 9: 0.04925865445137024
[2025-02-10 00:44:02,423][flwr][INFO] - 		round 10: 0.043669030344486236
[2025-02-10 00:44:02,423][flwr][INFO] - 		round 11: 0.03877113295197487
[2025-02-10 00:44:02,423][flwr][INFO] - 		round 12: 0.034339886343479155
[2025-02-10 00:44:02,423][flwr][INFO] - 		round 13: 0.0313410772383213
[2025-02-10 00:44:02,423][flwr][INFO] - 		round 14: 0.028417218846082688
[2025-02-10 00:44:02,423][flwr][INFO] - 		round 15: 0.02645457138121128
[2025-02-10 00:44:02,423][flwr][INFO] - 		round 16: 0.024103290197253227
[2025-02-10 00:44:02,423][flwr][INFO] - 		round 17: 0.023280841091275217
[2025-02-10 00:44:02,423][flwr][INFO] - 		round 18: 0.022583679005503655
[2025-02-10 00:44:02,423][flwr][INFO] - 		round 19: 0.02162578456699848
[2025-02-10 00:44:02,424][flwr][INFO] - 		round 20: 0.02055426798313856
[2025-02-10 00:44:02,424][flwr][INFO] - 	History (metrics, distributed, fit):
[2025-02-10 00:44:02,424][flwr][INFO] - 	{'clients_epsilons': [(1, 0.6813471387867436),
[2025-02-10 00:44:02,424][flwr][INFO] - 	                      (2, 0.6813471387867436),
[2025-02-10 00:44:02,424][flwr][INFO] - 	                      (3, 0.6813471387867436),
[2025-02-10 00:44:02,424][flwr][INFO] - 	                      (4, 0.6813471387867436),
[2025-02-10 00:44:02,424][flwr][INFO] - 	                      (5, 0.6813471387867436),
[2025-02-10 00:44:02,424][flwr][INFO] - 	                      (6, 0.6813471387867436),
[2025-02-10 00:44:02,424][flwr][INFO] - 	                      (7, 0.6813471387867436),
[2025-02-10 00:44:02,424][flwr][INFO] - 	                      (8, 0.6813471387867436),
[2025-02-10 00:44:02,424][flwr][INFO] - 	                      (9, 0.6813471387867436),
[2025-02-10 00:44:02,424][flwr][INFO] - 	                      (10, 0.6813471387867436),
[2025-02-10 00:44:02,424][flwr][INFO] - 	                      (11, 0.6813471387867436),
[2025-02-10 00:44:02,425][flwr][INFO] - 	                      (12, 0.6813471387867436),
[2025-02-10 00:44:02,425][flwr][INFO] - 	                      (13, 0.6813471387867436),
[2025-02-10 00:44:02,425][flwr][INFO] - 	                      (14, 0.6813471387867436),
[2025-02-10 00:44:02,425][flwr][INFO] - 	                      (15, 0.6813471387867436),
[2025-02-10 00:44:02,425][flwr][INFO] - 	                      (16, 0.6813471387867436),
[2025-02-10 00:44:02,425][flwr][INFO] - 	                      (17, 0.6813471387867436),
[2025-02-10 00:44:02,425][flwr][INFO] - 	                      (18, 0.6813471387867436),
[2025-02-10 00:44:02,425][flwr][INFO] - 	                      (19, 0.6813471387867436),
[2025-02-10 00:44:02,425][flwr][INFO] - 	                      (20, 0.6813471387867437)],
[2025-02-10 00:44:02,425][flwr][INFO] - 	 'clients_losses': [(1, 2.299075266520182),
[2025-02-10 00:44:02,425][flwr][INFO] - 	                    (2, 2.2880450375874837),
[2025-02-10 00:44:02,425][flwr][INFO] - 	                    (3, 2.2733247820536295),
[2025-02-10 00:44:02,425][flwr][INFO] - 	                    (4, 2.2468932549158733),
[2025-02-10 00:44:02,426][flwr][INFO] - 	                    (5, 2.2049834648768107),
[2025-02-10 00:44:02,426][flwr][INFO] - 	                    (6, 2.1338078117370607),
[2025-02-10 00:44:02,426][flwr][INFO] - 	                    (7, 2.0361741773287454),
[2025-02-10 00:44:02,426][flwr][INFO] - 	                    (8, 1.898864278793335),
[2025-02-10 00:44:02,426][flwr][INFO] - 	                    (9, 1.7273711856206257),
[2025-02-10 00:44:02,426][flwr][INFO] - 	                    (10, 1.553829296429952),
[2025-02-10 00:44:02,426][flwr][INFO] - 	                    (11, 1.3908761286735534),
[2025-02-10 00:44:02,426][flwr][INFO] - 	                    (12, 1.2424057626724243),
[2025-02-10 00:44:02,426][flwr][INFO] - 	                    (13, 1.126013526916504),
[2025-02-10 00:44:02,426][flwr][INFO] - 	                    (14, 1.023331680695216),
[2025-02-10 00:44:02,426][flwr][INFO] - 	                    (15, 0.9509314632415772),
[2025-02-10 00:44:02,426][flwr][INFO] - 	                    (16, 0.8816957592964172),
[2025-02-10 00:44:02,426][flwr][INFO] - 	                    (17, 0.8416421679655711),
[2025-02-10 00:44:02,427][flwr][INFO] - 	                    (18, 0.8067694201072058),
[2025-02-10 00:44:02,427][flwr][INFO] - 	                    (19, 0.7860479752222697),
[2025-02-10 00:44:02,427][flwr][INFO] - 	                    (20, 0.7363282223542531)]}
[2025-02-10 00:44:02,427][flwr][INFO] - 	History (metrics, distributed, evaluate):
[2025-02-10 00:44:02,427][flwr][INFO] - 	{'clients_accuracies': [(1, 0.10833333333333335),
[2025-02-10 00:44:02,427][flwr][INFO] - 	                        (2, 0.1675),
[2025-02-10 00:44:02,427][flwr][INFO] - 	                        (3, 0.37583333333333335),
[2025-02-10 00:44:02,427][flwr][INFO] - 	                        (4, 0.4125),
[2025-02-10 00:44:02,427][flwr][INFO] - 	                        (5, 0.39),
[2025-02-10 00:44:02,427][flwr][INFO] - 	                        (6, 0.45666666666666667),
[2025-02-10 00:44:02,427][flwr][INFO] - 	                        (7, 0.5349999999999999),
[2025-02-10 00:44:02,427][flwr][INFO] - 	                        (8, 0.6041666666666666),
[2025-02-10 00:44:02,427][flwr][INFO] - 	                        (9, 0.6383333333333333),
[2025-02-10 00:44:02,427][flwr][INFO] - 	                        (10, 0.6591666666666666),
[2025-02-10 00:44:02,428][flwr][INFO] - 	                        (11, 0.6758333333333333),
[2025-02-10 00:44:02,428][flwr][INFO] - 	                        (12, 0.6874999999999999),
[2025-02-10 00:44:02,428][flwr][INFO] - 	                        (13, 0.7058333333333333),
[2025-02-10 00:44:02,428][flwr][INFO] - 	                        (14, 0.71),
[2025-02-10 00:44:02,428][flwr][INFO] - 	                        (15, 0.7274999999999999),
[2025-02-10 00:44:02,428][flwr][INFO] - 	                        (16, 0.7474999999999999),
[2025-02-10 00:44:02,428][flwr][INFO] - 	                        (17, 0.7525000000000001),
[2025-02-10 00:44:02,428][flwr][INFO] - 	                        (18, 0.7491666666666666),
[2025-02-10 00:44:02,428][flwr][INFO] - 	                        (19, 0.7541666666666667),
[2025-02-10 00:44:02,428][flwr][INFO] - 	                        (20, 0.7758333333333334)],
[2025-02-10 00:44:02,428][flwr][INFO] - 	 'clients_losses': [(1, 0.07634576618671418),
[2025-02-10 00:44:02,428][flwr][INFO] - 	                    (2, 0.0759085504213969),
[2025-02-10 00:44:02,429][flwr][INFO] - 	                    (3, 0.07513303597768148),
[2025-02-10 00:44:02,429][flwr][INFO] - 	                    (4, 0.07391207794348399),
[2025-02-10 00:44:02,429][flwr][INFO] - 	                    (5, 0.0718961755434672),
[2025-02-10 00:44:02,429][flwr][INFO] - 	                    (6, 0.06879389464855193),
[2025-02-10 00:44:02,429][flwr][INFO] - 	                    (7, 0.06474245131015777),
[2025-02-10 00:44:02,429][flwr][INFO] - 	                    (8, 0.05896940290927888),
[2025-02-10 00:44:02,429][flwr][INFO] - 	                    (9, 0.052971772253513336),
[2025-02-10 00:44:02,429][flwr][INFO] - 	                    (10, 0.04723000874121984),
[2025-02-10 00:44:02,429][flwr][INFO] - 	                    (11, 0.04205681383609772),
[2025-02-10 00:44:02,429][flwr][INFO] - 	                    (12, 0.0373799038430055),
[2025-02-10 00:44:02,429][flwr][INFO] - 	                    (13, 0.03427125652631123),
[2025-02-10 00:44:02,429][flwr][INFO] - 	                    (14, 0.031176231751839322),
[2025-02-10 00:44:02,430][flwr][INFO] - 	                    (15, 0.029129256208737686),
[2025-02-10 00:44:02,430][flwr][INFO] - 	                    (16, 0.026265373031298323),
[2025-02-10 00:44:02,430][flwr][INFO] - 	                    (17, 0.025336717938383418),
[2025-02-10 00:44:02,430][flwr][INFO] - 	                    (18, 0.02444769303003947),
[2025-02-10 00:44:02,430][flwr][INFO] - 	                    (19, 0.023469489316145578),
[2025-02-10 00:44:02,430][flwr][INFO] - 	                    (20, 0.02214598298072815)]}
[2025-02-10 00:44:02,430][flwr][INFO] - 	History (metrics, centralized):
[2025-02-10 00:44:02,430][flwr][INFO] - 	{'accuracy': [(0, 0.0788),
[2025-02-10 00:44:02,430][flwr][INFO] - 	              (1, 0.1085),
[2025-02-10 00:44:02,430][flwr][INFO] - 	              (2, 0.1699),
[2025-02-10 00:44:02,430][flwr][INFO] - 	              (3, 0.3692),
[2025-02-10 00:44:02,430][flwr][INFO] - 	              (4, 0.4022),
[2025-02-10 00:44:02,430][flwr][INFO] - 	              (5, 0.3911),
[2025-02-10 00:44:02,431][flwr][INFO] - 	              (6, 0.4648),
[2025-02-10 00:44:02,431][flwr][INFO] - 	              (7, 0.5363),
[2025-02-10 00:44:02,431][flwr][INFO] - 	              (8, 0.5929),
[2025-02-10 00:44:02,431][flwr][INFO] - 	              (9, 0.6296),
[2025-02-10 00:44:02,431][flwr][INFO] - 	              (10, 0.6694),
[2025-02-10 00:44:02,431][flwr][INFO] - 	              (11, 0.6735),
[2025-02-10 00:44:02,431][flwr][INFO] - 	              (12, 0.7032),
[2025-02-10 00:44:02,431][flwr][INFO] - 	              (13, 0.7067),
[2025-02-10 00:44:02,431][flwr][INFO] - 	              (14, 0.7151),
[2025-02-10 00:44:02,431][flwr][INFO] - 	              (15, 0.739),
[2025-02-10 00:44:02,431][flwr][INFO] - 	              (16, 0.7515),
[2025-02-10 00:44:02,431][flwr][INFO] - 	              (17, 0.7584),
[2025-02-10 00:44:02,432][flwr][INFO] - 	              (18, 0.7532),
[2025-02-10 00:44:02,432][flwr][INFO] - 	              (19, 0.7606),
[2025-02-10 00:44:02,432][flwr][INFO] - 	              (20, 0.7811)]}
[2025-02-10 00:44:02,432][flwr][INFO] - 
