[2025-02-17 21:16:59,863][flwr][INFO] - Starting Flower ServerApp, config: num_rounds=20, no round_timeout
[2025-02-17 21:16:59,864][flwr][INFO] - 
[2025-02-17 21:16:59,865][flwr][INFO] - [INIT]
[2025-02-17 21:16:59,866][flwr][INFO] - Using initial global parameters provided by strategy
[2025-02-17 21:16:59,867][flwr][INFO] - Starting evaluation of initial global parameters
[2025-02-17 21:17:06,196][flwr][INFO] - initial parameters (loss, other metrics): 0.07218380236625671, {'accuracy': 0.0859}
[2025-02-17 21:17:06,198][flwr][INFO] - 
[2025-02-17 21:17:06,198][flwr][INFO] - [ROUND 1]
[2025-02-17 21:17:06,198][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 21:17:48,770][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-17 21:17:53,633][flwr][INFO] - fit progress: (1, 0.07160039765834808, {'accuracy': 0.1974}, 47.43518535699695)
[2025-02-17 21:17:53,633][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 21:18:10,321][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 21:18:10,322][flwr][INFO] - 
[2025-02-17 21:18:10,322][flwr][INFO] - [ROUND 2]
[2025-02-17 21:18:10,322][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 21:18:47,150][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-17 21:18:51,668][flwr][INFO] - fit progress: (2, 0.07073744406700135, {'accuracy': 0.3105}, 105.4704239119892)
[2025-02-17 21:18:51,669][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 21:19:10,396][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 21:19:10,396][flwr][INFO] - 
[2025-02-17 21:19:10,396][flwr][INFO] - [ROUND 3]
[2025-02-17 21:19:10,397][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 21:19:56,360][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-17 21:20:00,975][flwr][INFO] - fit progress: (3, 0.06883396527767181, {'accuracy': 0.3672}, 174.77742141700583)
[2025-02-17 21:20:00,976][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 21:20:24,638][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 21:20:24,638][flwr][INFO] - 
[2025-02-17 21:20:24,639][flwr][INFO] - [ROUND 4]
[2025-02-17 21:20:24,639][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 21:21:03,392][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-17 21:21:07,977][flwr][INFO] - fit progress: (4, 0.06472387603521347, {'accuracy': 0.4694}, 241.77891938298126)
[2025-02-17 21:21:07,977][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 21:21:40,132][flwr][ERROR] - An exception was raised when processing a message by RayBackend
[2025-02-17 21:21:40,133][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=28144, ip=172.27.85.201, actor_id=1827950fb90e565c0791ef4d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fe9d8132ed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=28144, ip=172.27.85.201, actor_id=1827950fb90e565c0791ef4d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fe9d8132ed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=28144, ip=172.27.85.201, actor_id=1827950fb90e565c0791ef4d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fe9d8132ed0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c
[2025-02-17 21:21:40,135][flwr][ERROR] - Traceback (most recent call last):
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py", line 112, in worker
    out_mssg, updated_context = backend.process_message(message, context)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 187, in process_message
    raise ex
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 175, in process_message
    ) = self.pool.fetch_result_and_return_actor_to_pool(future)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 478, in fetch_result_and_return_actor_to_pool
    _, out_mssg, updated_context = ray.get(future)
                                   ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=28144, ip=172.27.85.201, actor_id=1827950fb90e565c0791ef4d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fe9d8132ed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=28144, ip=172.27.85.201, actor_id=1827950fb90e565c0791ef4d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fe9d8132ed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=28144, ip=172.27.85.201, actor_id=1827950fb90e565c0791ef4d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fe9d8132ed0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

[2025-02-17 21:21:47,883][flwr][ERROR] - An exception was raised when processing a message by RayBackend
[2025-02-17 21:21:47,883][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=28143, ip=172.27.85.201, actor_id=f83fe2ef00ceeb2cb7f8678d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f675411aed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=28143, ip=172.27.85.201, actor_id=f83fe2ef00ceeb2cb7f8678d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f675411aed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=28143, ip=172.27.85.201, actor_id=f83fe2ef00ceeb2cb7f8678d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f675411aed0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c
[2025-02-17 21:21:47,884][flwr][ERROR] - Traceback (most recent call last):
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py", line 112, in worker
    out_mssg, updated_context = backend.process_message(message, context)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 187, in process_message
    raise ex
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 175, in process_message
    ) = self.pool.fetch_result_and_return_actor_to_pool(future)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 478, in fetch_result_and_return_actor_to_pool
    _, out_mssg, updated_context = ray.get(future)
                                   ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=28143, ip=172.27.85.201, actor_id=f83fe2ef00ceeb2cb7f8678d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f675411aed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=28143, ip=172.27.85.201, actor_id=f83fe2ef00ceeb2cb7f8678d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f675411aed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=28143, ip=172.27.85.201, actor_id=f83fe2ef00ceeb2cb7f8678d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f675411aed0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

[2025-02-17 21:21:51,960][flwr][ERROR] - An exception was raised when processing a message by RayBackend
[2025-02-17 21:21:51,960][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=28146, ip=172.27.85.201, actor_id=f3eaf3eb9a128d1ffb05d1b101000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f479461eed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=28146, ip=172.27.85.201, actor_id=f3eaf3eb9a128d1ffb05d1b101000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f479461eed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=28146, ip=172.27.85.201, actor_id=f3eaf3eb9a128d1ffb05d1b101000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f479461eed0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c
[2025-02-17 21:21:51,961][flwr][ERROR] - Traceback (most recent call last):
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py", line 112, in worker
    out_mssg, updated_context = backend.process_message(message, context)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 187, in process_message
    raise ex
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 175, in process_message
    ) = self.pool.fetch_result_and_return_actor_to_pool(future)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 478, in fetch_result_and_return_actor_to_pool
    _, out_mssg, updated_context = ray.get(future)
                                   ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=28146, ip=172.27.85.201, actor_id=f3eaf3eb9a128d1ffb05d1b101000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f479461eed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=28146, ip=172.27.85.201, actor_id=f3eaf3eb9a128d1ffb05d1b101000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f479461eed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=28146, ip=172.27.85.201, actor_id=f3eaf3eb9a128d1ffb05d1b101000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f479461eed0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

[2025-02-17 21:21:59,200][flwr][ERROR] - An exception was raised when processing a message by RayBackend
[2025-02-17 21:21:59,200][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=28145, ip=172.27.85.201, actor_id=f9e5220288e63837a0181fd101000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9014422fd0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=28145, ip=172.27.85.201, actor_id=f9e5220288e63837a0181fd101000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9014422fd0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=28145, ip=172.27.85.201, actor_id=f9e5220288e63837a0181fd101000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9014422fd0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c
[2025-02-17 21:21:59,201][flwr][ERROR] - Traceback (most recent call last):
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py", line 112, in worker
    out_mssg, updated_context = backend.process_message(message, context)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 187, in process_message
    raise ex
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 175, in process_message
    ) = self.pool.fetch_result_and_return_actor_to_pool(future)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 478, in fetch_result_and_return_actor_to_pool
    _, out_mssg, updated_context = ray.get(future)
                                   ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=28145, ip=172.27.85.201, actor_id=f9e5220288e63837a0181fd101000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9014422fd0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=28145, ip=172.27.85.201, actor_id=f9e5220288e63837a0181fd101000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9014422fd0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=28145, ip=172.27.85.201, actor_id=f9e5220288e63837a0181fd101000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9014422fd0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

[2025-02-17 21:22:03,619][flwr][ERROR] - An exception was raised when processing a message by RayBackend
[2025-02-17 21:22:03,620][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=28143, ip=172.27.85.201, actor_id=f83fe2ef00ceeb2cb7f8678d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f675411aed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=28143, ip=172.27.85.201, actor_id=f83fe2ef00ceeb2cb7f8678d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f675411aed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=28143, ip=172.27.85.201, actor_id=f83fe2ef00ceeb2cb7f8678d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f675411aed0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c
[2025-02-17 21:22:03,620][flwr][ERROR] - Traceback (most recent call last):
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py", line 112, in worker
    out_mssg, updated_context = backend.process_message(message, context)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 187, in process_message
    raise ex
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py", line 175, in process_message
    ) = self.pool.fetch_result_and_return_actor_to_pool(future)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 478, in fetch_result_and_return_actor_to_pool
    _, out_mssg, updated_context = ray.get(future)
                                   ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=28143, ip=172.27.85.201, actor_id=f83fe2ef00ceeb2cb7f8678d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f675411aed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=28143, ip=172.27.85.201, actor_id=f83fe2ef00ceeb2cb7f8678d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f675411aed0>)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/client/message_handler/message_handler.py", line 96, in handle_legacy_message_from_msgtype
    client = client_fn(context)
             ^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/client_utils.py", line 201, in client_fn
    trainloader, valloader, _= load_datasets(cfg, partition_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/Diplomatic_incident/Differential_Privacy/Mnist_2/opacus_fl/data_utils.py", line 27, in load_datasets
    partition = fds.load_partition(partition_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 177, in load_partition
    self._prepare_dataset()
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr_datasets/federated_dataset.py", line 314, in _prepare_dataset
    self._dataset = datasets.load_dataset(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/load.py", line 1890, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 342, in __init__
    self.config, self.config_id = self._create_builder_config(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 597, in _create_builder_config
    builder_config._resolve_data_files(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/builder.py", line 206, in _resolve_data_files
    self.data_files = self.data_files.resolve(base_path, download_config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 818, in resolve
    out[key] = data_files_patterns_list.resolve(base_path, download_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 771, in resolve
    resolve_pattern(
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/datasets/data_files.py", line 388, in resolve_pattern
    for filepath, info in fs.glob(pattern, detail=True, **glob_kwargs).items()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 521, in glob
    return super().glob(path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 611, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 556, in find
    return super().find(
           ^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/fsspec/spec.py", line 502, in find
    out[path] = self.info(path)
                ^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 719, in info
    paths_info = self._api.get_paths_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3303, in get_paths_info
    hf_raise_for_status(response)
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 477, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=28143, ip=172.27.85.201, actor_id=f83fe2ef00ceeb2cb7f8678d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f675411aed0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo_ubuntu/miniconda3/envs/flwr_25_DP/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/ylecun/mnist/paths-info/77f3279092a1c1579b2250db8eafed0ad422088c

[2025-02-17 21:22:05,172][flwr][INFO] - aggregate_evaluate: received 45 results and 5 failures
[2025-02-17 21:22:05,173][flwr][INFO] - 
[2025-02-17 21:22:05,173][flwr][INFO] - [ROUND 5]
[2025-02-17 21:22:05,173][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 21:22:44,941][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-17 21:22:49,331][flwr][INFO] - fit progress: (5, 0.05693035832643509, {'accuracy': 0.5299}, 343.1334024569951)
[2025-02-17 21:22:49,332][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 21:23:11,397][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 21:23:11,398][flwr][INFO] - 
[2025-02-17 21:23:11,398][flwr][INFO] - [ROUND 6]
[2025-02-17 21:23:11,398][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 21:23:52,240][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-17 21:23:57,028][flwr][INFO] - fit progress: (6, 0.046522416174411774, {'accuracy': 0.5826}, 410.8304633779917)
[2025-02-17 21:23:57,029][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 21:24:15,978][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 21:24:15,978][flwr][INFO] - 
[2025-02-17 21:24:15,978][flwr][INFO] - [ROUND 7]
[2025-02-17 21:24:15,979][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 21:24:54,213][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-17 21:24:58,667][flwr][INFO] - fit progress: (7, 0.03783001360297203, {'accuracy': 0.6126}, 472.4687810309988)
[2025-02-17 21:24:58,667][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 21:25:16,042][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 21:25:16,042][flwr][INFO] - 
[2025-02-17 21:25:16,042][flwr][INFO] - [ROUND 8]
[2025-02-17 21:25:16,043][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 21:25:53,777][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-17 21:25:58,345][flwr][INFO] - fit progress: (8, 0.03345410489439964, {'accuracy': 0.6438}, 532.1470094709948)
[2025-02-17 21:25:58,345][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 21:26:18,625][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 21:26:18,625][flwr][INFO] - 
[2025-02-17 21:26:18,626][flwr][INFO] - [ROUND 9]
[2025-02-17 21:26:18,626][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 21:26:58,510][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-17 21:27:07,990][flwr][INFO] - fit progress: (9, 0.03287599022984505, {'accuracy': 0.6717}, 601.7925368800061)
[2025-02-17 21:27:07,991][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 21:27:33,049][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 21:27:33,050][flwr][INFO] - 
[2025-02-17 21:27:33,050][flwr][INFO] - [ROUND 10]
[2025-02-17 21:27:33,050][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 21:28:13,810][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-17 21:28:18,800][flwr][INFO] - fit progress: (10, 0.035574621367454526, {'accuracy': 0.6791}, 672.6017093859846)
[2025-02-17 21:28:18,800][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 21:28:36,842][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 21:28:36,843][flwr][INFO] - 
[2025-02-17 21:28:36,843][flwr][INFO] - [ROUND 11]
[2025-02-17 21:28:36,843][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 21:29:13,971][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-17 21:29:19,621][flwr][INFO] - fit progress: (11, 0.0414121315330267, {'accuracy': 0.678}, 733.4230807679996)
[2025-02-17 21:29:19,621][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 21:29:37,710][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 21:29:37,710][flwr][INFO] - 
[2025-02-17 21:29:37,710][flwr][INFO] - [ROUND 12]
[2025-02-17 21:29:37,710][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 21:30:17,654][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-17 21:30:21,882][flwr][INFO] - fit progress: (12, 0.05074385612308979, {'accuracy': 0.6739}, 795.6844432459911)
[2025-02-17 21:30:21,883][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 21:30:39,040][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 21:30:39,041][flwr][INFO] - 
[2025-02-17 21:30:39,041][flwr][INFO] - [ROUND 13]
[2025-02-17 21:30:39,041][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 21:31:18,923][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-17 21:31:23,186][flwr][INFO] - fit progress: (13, 0.06397509496212006, {'accuracy': 0.6671}, 856.9880583359918)
[2025-02-17 21:31:23,186][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 21:31:39,532][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 21:31:39,532][flwr][INFO] - 
[2025-02-17 21:31:39,532][flwr][INFO] - [ROUND 14]
[2025-02-17 21:31:39,533][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 21:32:17,819][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-17 21:32:22,228][flwr][INFO] - fit progress: (14, 0.08184561121463775, {'accuracy': 0.6555}, 916.0306094170082)
[2025-02-17 21:32:22,229][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 21:32:46,222][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 21:32:46,222][flwr][INFO] - 
[2025-02-17 21:32:46,222][flwr][INFO] - [ROUND 15]
[2025-02-17 21:32:46,223][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 21:33:24,645][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-17 21:33:29,187][flwr][INFO] - fit progress: (15, 0.10505827236175537, {'accuracy': 0.6416}, 982.9891417089966)
[2025-02-17 21:33:29,187][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 21:33:45,865][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 21:33:45,866][flwr][INFO] - 
[2025-02-17 21:33:45,866][flwr][INFO] - [ROUND 16]
[2025-02-17 21:33:45,866][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 21:34:24,202][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-17 21:34:28,634][flwr][INFO] - fit progress: (16, 0.1344725089609623, {'accuracy': 0.6285}, 1042.4361590599874)
[2025-02-17 21:34:28,634][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 21:34:48,646][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 21:34:48,647][flwr][INFO] - 
[2025-02-17 21:34:48,647][flwr][INFO] - [ROUND 17]
[2025-02-17 21:34:48,647][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 21:35:27,311][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-17 21:35:31,744][flwr][INFO] - fit progress: (17, 0.17071036546230317, {'accuracy': 0.616}, 1105.5459888449986)
[2025-02-17 21:35:31,744][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 21:35:47,290][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 21:35:47,290][flwr][INFO] - 
[2025-02-17 21:35:47,290][flwr][INFO] - [ROUND 18]
[2025-02-17 21:35:47,290][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 21:36:23,203][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-17 21:36:30,043][flwr][INFO] - fit progress: (18, 0.21473930755853654, {'accuracy': 0.6056}, 1163.844748404983)
[2025-02-17 21:36:30,043][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 21:36:47,137][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 21:36:47,138][flwr][INFO] - 
[2025-02-17 21:36:47,138][flwr][INFO] - [ROUND 19]
[2025-02-17 21:36:47,138][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 21:37:25,364][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-17 21:37:29,798][flwr][INFO] - fit progress: (19, 0.26764424986839297, {'accuracy': 0.5944}, 1223.599861641007)
[2025-02-17 21:37:29,798][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 21:37:45,279][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 21:37:45,279][flwr][INFO] - 
[2025-02-17 21:37:45,279][flwr][INFO] - [ROUND 20]
[2025-02-17 21:37:45,280][flwr][INFO] - configure_fit: strategy sampled 50 clients (out of 50)
[2025-02-17 21:38:23,397][flwr][INFO] - aggregate_fit: received 50 results and 0 failures
[2025-02-17 21:38:27,529][flwr][INFO] - fit progress: (20, 0.33046033842563627, {'accuracy': 0.5845}, 1281.3306318839896)
[2025-02-17 21:38:27,529][flwr][INFO] - configure_evaluate: strategy sampled 50 clients (out of 50)
[2025-02-17 21:38:43,335][flwr][INFO] - aggregate_evaluate: received 50 results and 0 failures
[2025-02-17 21:38:43,336][flwr][INFO] - 
[2025-02-17 21:38:43,336][flwr][INFO] - [SUMMARY]
[2025-02-17 21:38:43,336][flwr][INFO] - Run finished 20 round(s) in 1297.14s
[2025-02-17 21:38:43,337][flwr][INFO] - 	History (loss, distributed):
[2025-02-17 21:38:43,337][flwr][INFO] - 		round 1: 0.07626505482196806
[2025-02-17 21:38:43,337][flwr][INFO] - 		round 2: 0.07535862823327383
[2025-02-17 21:38:43,337][flwr][INFO] - 		round 3: 0.07337063316504161
[2025-02-17 21:38:43,337][flwr][INFO] - 		round 4: 0.06905354402683397
[2025-02-17 21:38:43,337][flwr][INFO] - 		round 5: 0.060968301892280585
[2025-02-17 21:38:43,338][flwr][INFO] - 		round 6: 0.05015078608194986
[2025-02-17 21:38:43,338][flwr][INFO] - 		round 7: 0.04122267378369966
[2025-02-17 21:38:43,338][flwr][INFO] - 		round 8: 0.03676942473649978
[2025-02-17 21:38:43,338][flwr][INFO] - 		round 9: 0.03619322777787844
[2025-02-17 21:38:43,338][flwr][INFO] - 		round 10: 0.03923179826140403
[2025-02-17 21:38:43,338][flwr][INFO] - 		round 11: 0.04569974616666636
[2025-02-17 21:38:43,338][flwr][INFO] - 		round 12: 0.05587654851873714
[2025-02-17 21:38:43,338][flwr][INFO] - 		round 13: 0.07006840676069259
[2025-02-17 21:38:43,338][flwr][INFO] - 		round 14: 0.08909682544072471
[2025-02-17 21:38:43,338][flwr][INFO] - 		round 15: 0.11354362602035206
[2025-02-17 21:38:43,338][flwr][INFO] - 		round 16: 0.1443734273513159
[2025-02-17 21:38:43,338][flwr][INFO] - 		round 17: 0.1822616313099861
[2025-02-17 21:38:43,338][flwr][INFO] - 		round 18: 0.2283325604597728
[2025-02-17 21:38:43,338][flwr][INFO] - 		round 19: 0.28343250624338784
[2025-02-17 21:38:43,339][flwr][INFO] - 		round 20: 0.34932246061166133
[2025-02-17 21:38:43,339][flwr][INFO] - 	History (loss, centralized):
[2025-02-17 21:38:43,339][flwr][INFO] - 		round 0: 0.07218380236625671
[2025-02-17 21:38:43,339][flwr][INFO] - 		round 1: 0.07160039765834808
[2025-02-17 21:38:43,339][flwr][INFO] - 		round 2: 0.07073744406700135
[2025-02-17 21:38:43,339][flwr][INFO] - 		round 3: 0.06883396527767181
[2025-02-17 21:38:43,339][flwr][INFO] - 		round 4: 0.06472387603521347
[2025-02-17 21:38:43,339][flwr][INFO] - 		round 5: 0.05693035832643509
[2025-02-17 21:38:43,339][flwr][INFO] - 		round 6: 0.046522416174411774
[2025-02-17 21:38:43,339][flwr][INFO] - 		round 7: 0.03783001360297203
[2025-02-17 21:38:43,339][flwr][INFO] - 		round 8: 0.03345410489439964
[2025-02-17 21:38:43,339][flwr][INFO] - 		round 9: 0.03287599022984505
[2025-02-17 21:38:43,339][flwr][INFO] - 		round 10: 0.035574621367454526
[2025-02-17 21:38:43,340][flwr][INFO] - 		round 11: 0.0414121315330267
[2025-02-17 21:38:43,340][flwr][INFO] - 		round 12: 0.05074385612308979
[2025-02-17 21:38:43,340][flwr][INFO] - 		round 13: 0.06397509496212006
[2025-02-17 21:38:43,340][flwr][INFO] - 		round 14: 0.08184561121463775
[2025-02-17 21:38:43,340][flwr][INFO] - 		round 15: 0.10505827236175537
[2025-02-17 21:38:43,340][flwr][INFO] - 		round 16: 0.1344725089609623
[2025-02-17 21:38:43,340][flwr][INFO] - 		round 17: 0.17071036546230317
[2025-02-17 21:38:43,340][flwr][INFO] - 		round 18: 0.21473930755853654
[2025-02-17 21:38:43,340][flwr][INFO] - 		round 19: 0.26764424986839297
[2025-02-17 21:38:43,340][flwr][INFO] - 		round 20: 0.33046033842563627
[2025-02-17 21:38:43,340][flwr][INFO] - 	History (metrics, distributed, fit):
[2025-02-17 21:38:43,340][flwr][INFO] - 	{'clients_epsilons': [(1, 1.0),
[2025-02-17 21:38:43,341][flwr][INFO] - 	                      (2, 1.0),
[2025-02-17 21:38:43,341][flwr][INFO] - 	                      (3, 1.0),
[2025-02-17 21:38:43,341][flwr][INFO] - 	                      (4, 1.0),
[2025-02-17 21:38:43,341][flwr][INFO] - 	                      (5, 1.0),
[2025-02-17 21:38:43,341][flwr][INFO] - 	                      (6, 1.0),
[2025-02-17 21:38:43,341][flwr][INFO] - 	                      (7, 1.0),
[2025-02-17 21:38:43,341][flwr][INFO] - 	                      (8, 1.0),
[2025-02-17 21:38:43,341][flwr][INFO] - 	                      (9, 1.0),
[2025-02-17 21:38:43,341][flwr][INFO] - 	                      (10, 1.0),
[2025-02-17 21:38:43,341][flwr][INFO] - 	                      (11, 1.0),
[2025-02-17 21:38:43,341][flwr][INFO] - 	                      (12, 1.0),
[2025-02-17 21:38:43,341][flwr][INFO] - 	                      (13, 1.0),
[2025-02-17 21:38:43,342][flwr][INFO] - 	                      (14, 1.0),
[2025-02-17 21:38:43,342][flwr][INFO] - 	                      (15, 1.0),
[2025-02-17 21:38:43,342][flwr][INFO] - 	                      (16, 1.0),
[2025-02-17 21:38:43,342][flwr][INFO] - 	                      (17, 1.0),
[2025-02-17 21:38:43,342][flwr][INFO] - 	                      (18, 1.0),
[2025-02-17 21:38:43,342][flwr][INFO] - 	                      (19, 1.0),
[2025-02-17 21:38:43,342][flwr][INFO] - 	                      (20, 1.0)],
[2025-02-17 21:38:43,342][flwr][INFO] - 	 'clients_losses': [(1, 2.2985936619440714),
[2025-02-17 21:38:43,342][flwr][INFO] - 	                    (2, 2.278652599652608),
[2025-02-17 21:38:43,342][flwr][INFO] - 	                    (3, 2.2422787866592406),
[2025-02-17 21:38:43,342][flwr][INFO] - 	                    (4, 2.1621740368207294),
[2025-02-17 21:38:43,342][flwr][INFO] - 	                    (5, 1.995320116519928),
[2025-02-17 21:38:43,343][flwr][INFO] - 	                    (6, 1.722259648958842),
[2025-02-17 21:38:43,343][flwr][INFO] - 	                    (7, 1.4186600058873495),
[2025-02-17 21:38:43,343][flwr][INFO] - 	                    (8, 1.2055029714107512),
[2025-02-17 21:38:43,343][flwr][INFO] - 	                    (9, 1.1212249972820283),
[2025-02-17 21:38:43,343][flwr][INFO] - 	                    (10, 1.1585091536442438),
[2025-02-17 21:38:43,343][flwr][INFO] - 	                    (11, 1.3034135902722677),
[2025-02-17 21:38:43,343][flwr][INFO] - 	                    (12, 1.5577079177300135),
[2025-02-17 21:38:43,343][flwr][INFO] - 	                    (13, 1.9294516115585962),
[2025-02-17 21:38:43,343][flwr][INFO] - 	                    (14, 2.441535948395729),
[2025-02-17 21:38:43,343][flwr][INFO] - 	                    (15, 3.111489194949468),
[2025-02-17 21:38:43,343][flwr][INFO] - 	                    (16, 3.9699086406230926),
[2025-02-17 21:38:43,343][flwr][INFO] - 	                    (17, 5.0392430286407475),
[2025-02-17 21:38:43,344][flwr][INFO] - 	                    (18, 6.343765632947286),
[2025-02-17 21:38:43,344][flwr][INFO] - 	                    (19, 7.921905921300252),
[2025-02-17 21:38:43,344][flwr][INFO] - 	                    (20, 9.809261132876077)]}
[2025-02-17 21:38:43,344][flwr][INFO] - 	History (metrics, distributed, evaluate):
[2025-02-17 21:38:43,344][flwr][INFO] - 	{'clients_accuracies': [(1, 0.19166666666666668),
[2025-02-17 21:38:43,344][flwr][INFO] - 	                        (2, 0.3096666666666666),
[2025-02-17 21:38:43,344][flwr][INFO] - 	                        (3, 0.3713333333333332),
[2025-02-17 21:38:43,344][flwr][INFO] - 	                        (4, 0.4722222222222223),
[2025-02-17 21:38:43,344][flwr][INFO] - 	                        (5, 0.5246666666666666),
[2025-02-17 21:38:43,344][flwr][INFO] - 	                        (6, 0.5713333333333334),
[2025-02-17 21:38:43,344][flwr][INFO] - 	                        (7, 0.6044999999999999),
[2025-02-17 21:38:43,345][flwr][INFO] - 	                        (8, 0.6333333333333333),
[2025-02-17 21:38:43,345][flwr][INFO] - 	                        (9, 0.6583333333333333),
[2025-02-17 21:38:43,345][flwr][INFO] - 	                        (10, 0.6679999999999999),
[2025-02-17 21:38:43,345][flwr][INFO] - 	                        (11, 0.6753333333333333),
[2025-02-17 21:38:43,345][flwr][INFO] - 	                        (12, 0.6673333333333332),
[2025-02-17 21:38:43,345][flwr][INFO] - 	                        (13, 0.6638333333333332),
[2025-02-17 21:38:43,345][flwr][INFO] - 	                        (14, 0.6533333333333333),
[2025-02-17 21:38:43,345][flwr][INFO] - 	                        (15, 0.6415000000000001),
[2025-02-17 21:38:43,345][flwr][INFO] - 	                        (16, 0.6298333333333335),
[2025-02-17 21:38:43,345][flwr][INFO] - 	                        (17, 0.6163333333333333),
[2025-02-17 21:38:43,345][flwr][INFO] - 	                        (18, 0.6048333333333333),
[2025-02-17 21:38:43,345][flwr][INFO] - 	                        (19, 0.5913333333333332),
[2025-02-17 21:38:43,346][flwr][INFO] - 	                        (20, 0.5833333333333333)],
[2025-02-17 21:38:43,346][flwr][INFO] - 	 'clients_losses': [(1, 0.07626505482196806),
[2025-02-17 21:38:43,346][flwr][INFO] - 	                    (2, 0.07535862823327383),
[2025-02-17 21:38:43,346][flwr][INFO] - 	                    (3, 0.07337063316504161),
[2025-02-17 21:38:43,346][flwr][INFO] - 	                    (4, 0.06905354402683397),
[2025-02-17 21:38:43,346][flwr][INFO] - 	                    (5, 0.060968301892280585),
[2025-02-17 21:38:43,346][flwr][INFO] - 	                    (6, 0.05015078608194986),
[2025-02-17 21:38:43,346][flwr][INFO] - 	                    (7, 0.04122267378369966),
[2025-02-17 21:38:43,346][flwr][INFO] - 	                    (8, 0.03676942473649978),
[2025-02-17 21:38:43,346][flwr][INFO] - 	                    (9, 0.03619322777787844),
[2025-02-17 21:38:43,346][flwr][INFO] - 	                    (10, 0.03923179826140403),
[2025-02-17 21:38:43,346][flwr][INFO] - 	                    (11, 0.04569974616666636),
[2025-02-17 21:38:43,347][flwr][INFO] - 	                    (12, 0.05587654851873714),
[2025-02-17 21:38:43,347][flwr][INFO] - 	                    (13, 0.07006840676069259),
[2025-02-17 21:38:43,347][flwr][INFO] - 	                    (14, 0.08909682544072471),
[2025-02-17 21:38:43,347][flwr][INFO] - 	                    (15, 0.11354362602035206),
[2025-02-17 21:38:43,347][flwr][INFO] - 	                    (16, 0.1443734273513159),
[2025-02-17 21:38:43,347][flwr][INFO] - 	                    (17, 0.1822616313099861),
[2025-02-17 21:38:43,347][flwr][INFO] - 	                    (18, 0.2283325604597728),
[2025-02-17 21:38:43,347][flwr][INFO] - 	                    (19, 0.28343250624338784),
[2025-02-17 21:38:43,347][flwr][INFO] - 	                    (20, 0.34932246061166133)]}
[2025-02-17 21:38:43,347][flwr][INFO] - 	History (metrics, centralized):
[2025-02-17 21:38:43,348][flwr][INFO] - 	{'accuracy': [(0, 0.0859),
[2025-02-17 21:38:43,348][flwr][INFO] - 	              (1, 0.1974),
[2025-02-17 21:38:43,348][flwr][INFO] - 	              (2, 0.3105),
[2025-02-17 21:38:43,348][flwr][INFO] - 	              (3, 0.3672),
[2025-02-17 21:38:43,348][flwr][INFO] - 	              (4, 0.4694),
[2025-02-17 21:38:43,348][flwr][INFO] - 	              (5, 0.5299),
[2025-02-17 21:38:43,348][flwr][INFO] - 	              (6, 0.5826),
[2025-02-17 21:38:43,348][flwr][INFO] - 	              (7, 0.6126),
[2025-02-17 21:38:43,348][flwr][INFO] - 	              (8, 0.6438),
[2025-02-17 21:38:43,349][flwr][INFO] - 	              (9, 0.6717),
[2025-02-17 21:38:43,349][flwr][INFO] - 	              (10, 0.6791),
[2025-02-17 21:38:43,349][flwr][INFO] - 	              (11, 0.678),
[2025-02-17 21:38:43,349][flwr][INFO] - 	              (12, 0.6739),
[2025-02-17 21:38:43,349][flwr][INFO] - 	              (13, 0.6671),
[2025-02-17 21:38:43,349][flwr][INFO] - 	              (14, 0.6555),
[2025-02-17 21:38:43,349][flwr][INFO] - 	              (15, 0.6416),
[2025-02-17 21:38:43,349][flwr][INFO] - 	              (16, 0.6285),
[2025-02-17 21:38:43,349][flwr][INFO] - 	              (17, 0.616),
[2025-02-17 21:38:43,349][flwr][INFO] - 	              (18, 0.6056),
[2025-02-17 21:38:43,349][flwr][INFO] - 	              (19, 0.5944),
[2025-02-17 21:38:43,350][flwr][INFO] - 	              (20, 0.5845)]}
[2025-02-17 21:38:43,350][flwr][INFO] - 
